// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/lifecycle/dto.proto

package lifecyclev1

import (
	common "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            common.RequestStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=aether.platform.v1.common.RequestStatus" json:"status,omitempty"`
	CatalogItemId     string                 `protobuf:"bytes,3,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	EnvId             string                 `protobuf:"bytes,4,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,5,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BundleId          string                 `protobuf:"bytes,7,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FormValues        map[string]string      `protobuf:"bytes,8,rep,name=form_values,json=formValues,proto3" json:"form_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FormHash          string                 `protobuf:"bytes,9,opt,name=form_hash,json=formHash,proto3" json:"form_hash,omitempty"`
	Source            common.RequestSource   `protobuf:"varint,10,opt,name=source,proto3,enum=aether.platform.v1.common.RequestSource" json:"source,omitempty"`
	PinnedCommit      string                 `protobuf:"bytes,11,opt,name=pinned_commit,json=pinnedCommit,proto3" json:"pinned_commit,omitempty"`
	PlanArtifactId    string                 `protobuf:"bytes,12,opt,name=plan_artifact_id,json=planArtifactId,proto3" json:"plan_artifact_id,omitempty"`
	CostEstimateCents int64                  `protobuf:"varint,13,opt,name=cost_estimate_cents,json=costEstimateCents,proto3" json:"cost_estimate_cents,omitempty"`
	CostCurrency      string                 `protobuf:"bytes,14,opt,name=cost_currency,json=costCurrency,proto3" json:"cost_currency,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version           int32                  `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,18,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// requester_id: the identity that submitted the request. Required for
	// "my requests" queries and approver-side attribution (docs/04 §2.4).
	RequesterId string `protobuf:"bytes,19,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	// current_stage: human-readable pipeline stage within the current
	// status (e.g. "codegen", "plan", "apply"). Coarse-grained UI hint;
	// the authoritative state is `status` + `version` (docs/00 GetRequest).
	CurrentStage string `protobuf:"bytes,20,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	// resolved_params_json: D28 provenance audit. Each resolved variable
	// carries {value, source, rank, overridden_from, user_attempted_override}.
	// Approvers need this to understand "where did this vpc_id come from".
	ResolvedParamsJson string `protobuf:"bytes,21,opt,name=resolved_params_json,json=resolvedParamsJson,proto3" json:"resolved_params_json,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LifecycleRequest) GetStatus() common.RequestStatus {
	if x != nil {
		return x.Status
	}
	return common.RequestStatus(0)
}

func (x *LifecycleRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *LifecycleRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *LifecycleRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *LifecycleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LifecycleRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *LifecycleRequest) GetFormValues() map[string]string {
	if x != nil {
		return x.FormValues
	}
	return nil
}

func (x *LifecycleRequest) GetFormHash() string {
	if x != nil {
		return x.FormHash
	}
	return ""
}

func (x *LifecycleRequest) GetSource() common.RequestSource {
	if x != nil {
		return x.Source
	}
	return common.RequestSource(0)
}

func (x *LifecycleRequest) GetPinnedCommit() string {
	if x != nil {
		return x.PinnedCommit
	}
	return ""
}

func (x *LifecycleRequest) GetPlanArtifactId() string {
	if x != nil {
		return x.PlanArtifactId
	}
	return ""
}

func (x *LifecycleRequest) GetCostEstimateCents() int64 {
	if x != nil {
		return x.CostEstimateCents
	}
	return 0
}

func (x *LifecycleRequest) GetCostCurrency() string {
	if x != nil {
		return x.CostCurrency
	}
	return ""
}

func (x *LifecycleRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LifecycleRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *LifecycleRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LifecycleRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LifecycleRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *LifecycleRequest) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *LifecycleRequest) GetResolvedParamsJson() string {
	if x != nil {
		return x.ResolvedParamsJson
	}
	return ""
}

type LifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Actor         *common.Actor          `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// State-transition trajectory (docs/00 §3 events endpoint semantics).
	// from_status/to_status form the state-machine arc; stage + message
	// give human-readable context for the frontend timeline view.
	FromStatus    string `protobuf:"bytes,7,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string `protobuf:"bytes,8,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	Stage         string `protobuf:"bytes,9,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{1}
}

func (x *LifecycleEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LifecycleEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LifecycleEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LifecycleEvent) GetActor() *common.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *LifecycleEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *LifecycleEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LifecycleEvent) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *LifecycleEvent) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *LifecycleEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *LifecycleEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlanArtifact struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status            common.ArtifactStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=aether.platform.v1.common.ArtifactStatus" json:"status,omitempty"`
	PlanHash          string                 `protobuf:"bytes,4,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"`
	Summary           *PlanSummary           `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CostEstimateCents int64                  `protobuf:"varint,6,opt,name=cost_estimate_cents,json=costEstimateCents,proto3" json:"cost_estimate_cents,omitempty"`
	StorageUri        string                 `protobuf:"bytes,7,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// D21 plan/apply decoupling version-consistency fields (docs/00 §4.4,
	// docs/09 §5.2, docs/12 invariant 0). Apply sandbox MUST verify these
	// match the plan-time values before executing — prevents stale/tampered
	// plan application.
	Sha256               string `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`                                                           // plan binary hash (tamper check)
	PinnedCommit         string `protobuf:"bytes,11,opt,name=pinned_commit,json=pinnedCommit,proto3" json:"pinned_commit,omitempty"`                           // apply must checkout same commit
	ToolchainProfileHash string `protobuf:"bytes,12,opt,name=toolchain_profile_hash,json=toolchainProfileHash,proto3" json:"toolchain_profile_hash,omitempty"` // apply TF profile must match
	ProviderLockHash     string `protobuf:"bytes,13,opt,name=provider_lock_hash,json=providerLockHash,proto3" json:"provider_lock_hash,omitempty"`             // apply .terraform.lock.hcl must match
	TfVersionSha256      string `protobuf:"bytes,14,opt,name=tf_version_sha256,json=tfVersionSha256,proto3" json:"tf_version_sha256,omitempty"`                // apply terraform binary must match
	StackId              string `protobuf:"bytes,15,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`                                          // PathGenerator output (docs/09 §5.2)
	StateKey             string `protobuf:"bytes,16,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`                                       // PathGenerator output
	SizeBytes            int64  `protobuf:"varint,17,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`                                   // plan file size
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlanArtifact) Reset() {
	*x = PlanArtifact{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanArtifact) ProtoMessage() {}

func (x *PlanArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanArtifact.ProtoReflect.Descriptor instead.
func (*PlanArtifact) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{2}
}

func (x *PlanArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanArtifact) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlanArtifact) GetStatus() common.ArtifactStatus {
	if x != nil {
		return x.Status
	}
	return common.ArtifactStatus(0)
}

func (x *PlanArtifact) GetPlanHash() string {
	if x != nil {
		return x.PlanHash
	}
	return ""
}

func (x *PlanArtifact) GetSummary() *PlanSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *PlanArtifact) GetCostEstimateCents() int64 {
	if x != nil {
		return x.CostEstimateCents
	}
	return 0
}

func (x *PlanArtifact) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *PlanArtifact) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PlanArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PlanArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PlanArtifact) GetPinnedCommit() string {
	if x != nil {
		return x.PinnedCommit
	}
	return ""
}

func (x *PlanArtifact) GetToolchainProfileHash() string {
	if x != nil {
		return x.ToolchainProfileHash
	}
	return ""
}

func (x *PlanArtifact) GetProviderLockHash() string {
	if x != nil {
		return x.ProviderLockHash
	}
	return ""
}

func (x *PlanArtifact) GetTfVersionSha256() string {
	if x != nil {
		return x.TfVersionSha256
	}
	return ""
}

func (x *PlanArtifact) GetStackId() string {
	if x != nil {
		return x.StackId
	}
	return ""
}

func (x *PlanArtifact) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *PlanArtifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type PlanSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourcesToAdd     int32                  `protobuf:"varint,1,opt,name=resources_to_add,json=resourcesToAdd,proto3" json:"resources_to_add,omitempty"`
	ResourcesToChange  int32                  `protobuf:"varint,2,opt,name=resources_to_change,json=resourcesToChange,proto3" json:"resources_to_change,omitempty"`
	ResourcesToDestroy int32                  `protobuf:"varint,3,opt,name=resources_to_destroy,json=resourcesToDestroy,proto3" json:"resources_to_destroy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlanSummary) Reset() {
	*x = PlanSummary{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanSummary) ProtoMessage() {}

func (x *PlanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanSummary.ProtoReflect.Descriptor instead.
func (*PlanSummary) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{3}
}

func (x *PlanSummary) GetResourcesToAdd() int32 {
	if x != nil {
		return x.ResourcesToAdd
	}
	return 0
}

func (x *PlanSummary) GetResourcesToChange() int32 {
	if x != nil {
		return x.ResourcesToChange
	}
	return 0
}

func (x *PlanSummary) GetResourcesToDestroy() int32 {
	if x != nil {
		return x.ResourcesToDestroy
	}
	return 0
}

type GateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GateId        string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Severity      common.GateSeverity    `protobuf:"varint,5,opt,name=severity,proto3,enum=aether.platform.v1.common.GateSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResult) Reset() {
	*x = GateResult{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResult) ProtoMessage() {}

func (x *GateResult) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResult.ProtoReflect.Descriptor instead.
func (*GateResult) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{4}
}

func (x *GateResult) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GateResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GateResult) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *GateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GateResult) GetSeverity() common.GateSeverity {
	if x != nil {
		return x.Severity
	}
	return common.GateSeverity(0)
}

type ApprovalRun struct {
	state     protoimpl.MessageState   `protogen:"open.v1"`
	RunId     string                   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status    common.ApprovalRunStatus `protobuf:"varint,2,opt,name=status,proto3,enum=aether.platform.v1.common.ApprovalRunStatus" json:"status,omitempty"`
	DecidedBy string                   `protobuf:"bytes,3,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	DecidedAt string                   `protobuf:"bytes,4,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	// request_id: the request this run belongs to. Approvers navigate
	// from a run back to the request detail (docs/04 §2.10).
	RequestId string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// gate: which of the two mandatory gates this run is for (D21).
	// pre-plan = admission; pre-apply = execution confirmation.
	Gate common.ApprovalGate `protobuf:"varint,6,opt,name=gate,proto3,enum=aether.platform.v1.common.ApprovalGate" json:"gate,omitempty"`
	// current_node: the flow node currently awaiting decision
	// (docs/12 §7 node-chain visualization).
	CurrentNode string `protobuf:"bytes,7,opt,name=current_node,json=currentNode,proto3" json:"current_node,omitempty"`
	StartedAt   string `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt  string `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// expires_at: when the run (or its current node) times out and
	// escalates / auto-rejects (docs/12 §2.3 on_timeout).
	ExpiresAt string `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// version: optimistic lock for DecideApproval (CONC-003, docs/12a §5).
	// Client must pass expected_run_version = current version; server
	// rejects if stale (concurrent decision already advanced the version).
	Version       int32 `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRun) Reset() {
	*x = ApprovalRun{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRun) ProtoMessage() {}

func (x *ApprovalRun) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRun.ProtoReflect.Descriptor instead.
func (*ApprovalRun) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApprovalRun) GetStatus() common.ApprovalRunStatus {
	if x != nil {
		return x.Status
	}
	return common.ApprovalRunStatus(0)
}

func (x *ApprovalRun) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *ApprovalRun) GetDecidedAt() string {
	if x != nil {
		return x.DecidedAt
	}
	return ""
}

func (x *ApprovalRun) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApprovalRun) GetGate() common.ApprovalGate {
	if x != nil {
		return x.Gate
	}
	return common.ApprovalGate(0)
}

func (x *ApprovalRun) GetCurrentNode() string {
	if x != nil {
		return x.CurrentNode
	}
	return ""
}

func (x *ApprovalRun) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ApprovalRun) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ApprovalRun) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ApprovalRun) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ApprovalNodeRun is the runtime state of one node within an approval
// run (docs/04 §2.10 approval_node_runs). Drives the countersign
// progress UI (decided_count / required_count).
type ApprovalNodeRun struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	NodeId        string                    `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode          common.ApprovalNodeMode   `protobuf:"varint,2,opt,name=mode,proto3,enum=aether.platform.v1.common.ApprovalNodeMode" json:"mode,omitempty"`
	DecidedCount  int32                     `protobuf:"varint,3,opt,name=decided_count,json=decidedCount,proto3" json:"decided_count,omitempty"`
	RequiredCount int32                     `protobuf:"varint,4,opt,name=required_count,json=requiredCount,proto3" json:"required_count,omitempty"`
	Status        common.ApprovalNodeStatus `protobuf:"varint,5,opt,name=status,proto3,enum=aether.platform.v1.common.ApprovalNodeStatus" json:"status,omitempty"`
	TimeoutAt     string                    `protobuf:"bytes,6,opt,name=timeout_at,json=timeoutAt,proto3" json:"timeout_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalNodeRun) Reset() {
	*x = ApprovalNodeRun{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalNodeRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalNodeRun) ProtoMessage() {}

func (x *ApprovalNodeRun) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalNodeRun.ProtoReflect.Descriptor instead.
func (*ApprovalNodeRun) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{6}
}

func (x *ApprovalNodeRun) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ApprovalNodeRun) GetMode() common.ApprovalNodeMode {
	if x != nil {
		return x.Mode
	}
	return common.ApprovalNodeMode(0)
}

func (x *ApprovalNodeRun) GetDecidedCount() int32 {
	if x != nil {
		return x.DecidedCount
	}
	return 0
}

func (x *ApprovalNodeRun) GetRequiredCount() int32 {
	if x != nil {
		return x.RequiredCount
	}
	return 0
}

func (x *ApprovalNodeRun) GetStatus() common.ApprovalNodeStatus {
	if x != nil {
		return x.Status
	}
	return common.ApprovalNodeStatus(0)
}

func (x *ApprovalNodeRun) GetTimeoutAt() string {
	if x != nil {
		return x.TimeoutAt
	}
	return ""
}

// ApprovalDecisionRecord is one approver's decision on a node
// (docs/04 §2.10 approval_decisions). The audit trail within a run.
type ApprovalDecisionRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ApproverId    string                  `protobuf:"bytes,1,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Decision      common.ApprovalDecision `protobuf:"varint,2,opt,name=decision,proto3,enum=aether.platform.v1.common.ApprovalDecision" json:"decision,omitempty"`
	Comment       string                  `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	DecidedAt     string                  `protobuf:"bytes,4,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecisionRecord) Reset() {
	*x = ApprovalDecisionRecord{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecisionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecisionRecord) ProtoMessage() {}

func (x *ApprovalDecisionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecisionRecord.ProtoReflect.Descriptor instead.
func (*ApprovalDecisionRecord) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{7}
}

func (x *ApprovalDecisionRecord) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApprovalDecisionRecord) GetDecision() common.ApprovalDecision {
	if x != nil {
		return x.Decision
	}
	return common.ApprovalDecision(0)
}

func (x *ApprovalDecisionRecord) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ApprovalDecisionRecord) GetDecidedAt() string {
	if x != nil {
		return x.DecidedAt
	}
	return ""
}

type CreateRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogItemId string                 `protobuf:"bytes,1,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	EnvId         string                 `protobuf:"bytes,2,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BundleId      string                 `protobuf:"bytes,5,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FormValues    map[string]string      `protobuf:"bytes,6,rep,name=form_values,json=formValues,proto3" json:"form_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        common.RequestSource   `protobuf:"varint,7,opt,name=source,proto3,enum=aether.platform.v1.common.RequestSource" json:"source,omitempty"`
	SourceContext map[string]string      `protobuf:"bytes,8,rep,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequestRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *CreateRequestRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *CreateRequestRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateRequestRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateRequestRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *CreateRequestRequest) GetFormValues() map[string]string {
	if x != nil {
		return x.FormValues
	}
	return nil
}

func (x *CreateRequestRequest) GetSource() common.RequestSource {
	if x != nil {
		return x.Source
	}
	return common.RequestSource(0)
}

func (x *CreateRequestRequest) GetSourceContext() map[string]string {
	if x != nil {
		return x.SourceContext
	}
	return nil
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *LifecycleRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRequestResponse) GetRequest() *LifecycleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateRequestResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestRequest) Reset() {
	*x = GetRequestRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestRequest) ProtoMessage() {}

func (x *GetRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestRequest.ProtoReflect.Descriptor instead.
func (*GetRequestRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{10}
}

func (x *GetRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *LifecycleRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestResponse) Reset() {
	*x = GetRequestResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestResponse) ProtoMessage() {}

func (x *GetRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestResponse.ProtoReflect.Descriptor instead.
func (*GetRequestResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{11}
}

func (x *GetRequestResponse) GetRequest() *LifecycleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetRequestResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListRequestEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestEventsRequest) Reset() {
	*x = ListRequestEventsRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestEventsRequest) ProtoMessage() {}

func (x *ListRequestEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestEventsRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{12}
}

func (x *ListRequestEventsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListRequestEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequestEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRequestEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LifecycleEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestEventsResponse) Reset() {
	*x = ListRequestEventsResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestEventsResponse) ProtoMessage() {}

func (x *ListRequestEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestEventsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestEventsResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{13}
}

func (x *ListRequestEventsResponse) GetEvents() []*LifecycleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListRequestEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListRequestEventsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type CancelRequestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedVersion int32                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelRequestRequest) Reset() {
	*x = CancelRequestRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestRequest) ProtoMessage() {}

func (x *CancelRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestRequest.ProtoReflect.Descriptor instead.
func (*CancelRequestRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{14}
}

func (x *CancelRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelRequestRequest) GetExpectedVersion() int32 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CancelRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *LifecycleRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequestResponse) Reset() {
	*x = CancelRequestResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequestResponse) ProtoMessage() {}

func (x *CancelRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequestResponse.ProtoReflect.Descriptor instead.
func (*CancelRequestResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{15}
}

func (x *CancelRequestResponse) GetRequest() *LifecycleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CancelRequestResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type StartPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPlanRequest) Reset() {
	*x = StartPlanRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanRequest) ProtoMessage() {}

func (x *StartPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanRequest.ProtoReflect.Descriptor instead.
func (*StartPlanRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{16}
}

func (x *StartPlanRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StartPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *LifecycleRequest      `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPlanResponse) Reset() {
	*x = StartPlanResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanResponse) ProtoMessage() {}

func (x *StartPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanResponse.ProtoReflect.Descriptor instead.
func (*StartPlanResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{17}
}

func (x *StartPlanResponse) GetRequest() *LifecycleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StartPlanResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{18}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *PlanArtifact          `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{19}
}

func (x *GetArtifactResponse) GetArtifact() *PlanArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type EvaluateGateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGateRequest) Reset() {
	*x = EvaluateGateRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGateRequest) ProtoMessage() {}

func (x *EvaluateGateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateGateRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{20}
}

func (x *EvaluateGateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EvaluateGateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Gates         []*GateResult          `protobuf:"bytes,3,rep,name=gates,proto3" json:"gates,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGateResponse) Reset() {
	*x = EvaluateGateResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGateResponse) ProtoMessage() {}

func (x *EvaluateGateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateGateResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{21}
}

func (x *EvaluateGateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EvaluateGateResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *EvaluateGateResponse) GetGates() []*GateResult {
	if x != nil {
		return x.Gates
	}
	return nil
}

func (x *EvaluateGateResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type DecideApprovalRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	RunId              string                  `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Decision           common.ApprovalDecision `protobuf:"varint,2,opt,name=decision,proto3,enum=aether.platform.v1.common.ApprovalDecision" json:"decision,omitempty"`
	Comment            string                  `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ExpectedRunVersion int32                   `protobuf:"varint,4,opt,name=expected_run_version,json=expectedRunVersion,proto3" json:"expected_run_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DecideApprovalRequest) Reset() {
	*x = DecideApprovalRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideApprovalRequest) ProtoMessage() {}

func (x *DecideApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideApprovalRequest.ProtoReflect.Descriptor instead.
func (*DecideApprovalRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{22}
}

func (x *DecideApprovalRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *DecideApprovalRequest) GetDecision() common.ApprovalDecision {
	if x != nil {
		return x.Decision
	}
	return common.ApprovalDecision(0)
}

func (x *DecideApprovalRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *DecideApprovalRequest) GetExpectedRunVersion() int32 {
	if x != nil {
		return x.ExpectedRunVersion
	}
	return 0
}

type DecideApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ApprovalRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideApprovalResponse) Reset() {
	*x = DecideApprovalResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideApprovalResponse) ProtoMessage() {}

func (x *DecideApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideApprovalResponse.ProtoReflect.Descriptor instead.
func (*DecideApprovalResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{23}
}

func (x *DecideApprovalResponse) GetRun() *ApprovalRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *DecideApprovalResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type StartApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartApplyRequest) Reset() {
	*x = StartApplyRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartApplyRequest) ProtoMessage() {}

func (x *StartApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartApplyRequest.ProtoReflect.Descriptor instead.
func (*StartApplyRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{24}
}

func (x *StartApplyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StartApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartApplyResponse) Reset() {
	*x = StartApplyResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartApplyResponse) ProtoMessage() {}

func (x *StartApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartApplyResponse.ProtoReflect.Descriptor instead.
func (*StartApplyResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{25}
}

func (x *StartApplyResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters. All optional; unset fields match everything.
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	StatusFilter  []common.RequestStatus `protobuf:"varint,3,rep,packed,name=status_filter,json=statusFilter,proto3,enum=aether.platform.v1.common.RequestStatus" json:"status_filter,omitempty"`
	CatalogItemId string                 `protobuf:"bytes,4,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{26}
}

func (x *ListRequestsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ListRequestsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListRequestsRequest) GetStatusFilter() []common.RequestStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListRequestsRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *ListRequestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequestsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*LifecycleRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{27}
}

func (x *ListRequestsResponse) GetRequests() []*LifecycleRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListRequestsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListRequestsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListPendingApprovalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// approver_id: the identity asking for their queue. The server
	// resolves approver_id -> role_bindings to find runs whose current
	// node is routed to one of the caller's (team, role) pairs
	// (docs/12 §2.3 node binds role, not person).
	ApproverId string `protobuf:"bytes,1,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	// Optional narrowers.
	GateFilter    common.ApprovalGate `protobuf:"varint,2,opt,name=gate_filter,json=gateFilter,proto3,enum=aether.platform.v1.common.ApprovalGate" json:"gate_filter,omitempty"`
	TeamId        string              `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	PageSize      int32               `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string              `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsRequest) Reset() {
	*x = ListPendingApprovalsRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsRequest) ProtoMessage() {}

func (x *ListPendingApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{28}
}

func (x *ListPendingApprovalsRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ListPendingApprovalsRequest) GetGateFilter() common.ApprovalGate {
	if x != nil {
		return x.GateFilter
	}
	return common.ApprovalGate(0)
}

func (x *ListPendingApprovalsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListPendingApprovalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPendingApprovalsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPendingApprovalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*ApprovalRun         `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsResponse) Reset() {
	*x = ListPendingApprovalsResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsResponse) ProtoMessage() {}

func (x *ListPendingApprovalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{29}
}

func (x *ListPendingApprovalsResponse) GetRuns() []*ApprovalRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListPendingApprovalsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPendingApprovalsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetApprovalRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApprovalRunRequest) Reset() {
	*x = GetApprovalRunRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApprovalRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalRunRequest) ProtoMessage() {}

func (x *GetApprovalRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalRunRequest.ProtoReflect.Descriptor instead.
func (*GetApprovalRunRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{30}
}

func (x *GetApprovalRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetApprovalRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Run   *ApprovalRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	// nodes: the full node chain of the flow, with runtime progress
	// (docs/12 §7 frontend node-chain rendering).
	Nodes []*ApprovalNodeRun `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// decisions: the audit trail of decisions recorded so far.
	Decisions     []*ApprovalDecisionRecord `protobuf:"bytes,3,rep,name=decisions,proto3" json:"decisions,omitempty"`
	CorrelationId string                    `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApprovalRunResponse) Reset() {
	*x = GetApprovalRunResponse{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApprovalRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalRunResponse) ProtoMessage() {}

func (x *GetApprovalRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalRunResponse.ProtoReflect.Descriptor instead.
func (*GetApprovalRunResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{31}
}

func (x *GetApprovalRunResponse) GetRun() *ApprovalRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *GetApprovalRunResponse) GetNodes() []*ApprovalNodeRun {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetApprovalRunResponse) GetDecisions() []*ApprovalDecisionRecord {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *GetApprovalRunResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_platform_v1_lifecycle_dto_proto protoreflect.FileDescriptor

const file_platform_v1_lifecycle_dto_proto_rawDesc = "" +
	"\n" +
	"\x1fplatform/v1/lifecycle/dto.proto\x12\x1caether.platform.v1.lifecycle\x1a\x1cplatform/v1/common/dto.proto\x1a\x1dplatform/v1/common/enum.proto\"\x92\a\n" +
	"\x10LifecycleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.aether.platform.v1.common.RequestStatusR\x06status\x12&\n" +
	"\x0fcatalog_item_id\x18\x03 \x01(\tR\rcatalogItemId\x12\x15\n" +
	"\x06env_id\x18\x04 \x01(\tR\x05envId\x12\x17\n" +
	"\ateam_id\x18\x05 \x01(\tR\x06teamId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbundle_id\x18\a \x01(\tR\bbundleId\x12_\n" +
	"\vform_values\x18\b \x03(\v2>.aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntryR\n" +
	"formValues\x12\x1b\n" +
	"\tform_hash\x18\t \x01(\tR\bformHash\x12@\n" +
	"\x06source\x18\n" +
	" \x01(\x0e2(.aether.platform.v1.common.RequestSourceR\x06source\x12#\n" +
	"\rpinned_commit\x18\v \x01(\tR\fpinnedCommit\x12(\n" +
	"\x10plan_artifact_id\x18\f \x01(\tR\x0eplanArtifactId\x12.\n" +
	"\x13cost_estimate_cents\x18\r \x01(\x03R\x11costEstimateCents\x12#\n" +
	"\rcost_currency\x18\x0e \x01(\tR\fcostCurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x05R\aversion\x12%\n" +
	"\x0ecorrelation_id\x18\x12 \x01(\tR\rcorrelationId\x12!\n" +
	"\frequester_id\x18\x13 \x01(\tR\vrequesterId\x12#\n" +
	"\rcurrent_stage\x18\x14 \x01(\tR\fcurrentStage\x120\n" +
	"\x14resolved_params_json\x18\x15 \x01(\tR\x12resolvedParamsJson\x1a=\n" +
	"\x0fFormValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\x0eLifecycleEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x126\n" +
	"\x05actor\x18\x04 \x01(\v2 .aether.platform.v1.common.ActorR\x05actor\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12\x1f\n" +
	"\vfrom_status\x18\a \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\b \x01(\tR\btoStatus\x12\x14\n" +
	"\x05stage\x18\t \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\x95\x05\n" +
	"\fPlanArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).aether.platform.v1.common.ArtifactStatusR\x06status\x12\x1b\n" +
	"\tplan_hash\x18\x04 \x01(\tR\bplanHash\x12C\n" +
	"\asummary\x18\x05 \x01(\v2).aether.platform.v1.lifecycle.PlanSummaryR\asummary\x12.\n" +
	"\x13cost_estimate_cents\x18\x06 \x01(\x03R\x11costEstimateCents\x12\x1f\n" +
	"\vstorage_uri\x18\a \x01(\tR\n" +
	"storageUri\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\tR\x06sha256\x12#\n" +
	"\rpinned_commit\x18\v \x01(\tR\fpinnedCommit\x124\n" +
	"\x16toolchain_profile_hash\x18\f \x01(\tR\x14toolchainProfileHash\x12,\n" +
	"\x12provider_lock_hash\x18\r \x01(\tR\x10providerLockHash\x12*\n" +
	"\x11tf_version_sha256\x18\x0e \x01(\tR\x0ftfVersionSha256\x12\x19\n" +
	"\bstack_id\x18\x0f \x01(\tR\astackId\x12\x1b\n" +
	"\tstate_key\x18\x10 \x01(\tR\bstateKey\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x11 \x01(\x03R\tsizeBytes\"\x99\x01\n" +
	"\vPlanSummary\x12(\n" +
	"\x10resources_to_add\x18\x01 \x01(\x05R\x0eresourcesToAdd\x12.\n" +
	"\x13resources_to_change\x18\x02 \x01(\x05R\x11resourcesToChange\x120\n" +
	"\x14resources_to_destroy\x18\x03 \x01(\x05R\x12resourcesToDestroy\"\xb4\x01\n" +
	"\n" +
	"GateResult\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12C\n" +
	"\bseverity\x18\x05 \x01(\x0e2'.aether.platform.v1.common.GateSeverityR\bseverity\"\xa0\x03\n" +
	"\vApprovalRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12D\n" +
	"\x06status\x18\x02 \x01(\x0e2,.aether.platform.v1.common.ApprovalRunStatusR\x06status\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x03 \x01(\tR\tdecidedBy\x12\x1d\n" +
	"\n" +
	"decided_at\x18\x04 \x01(\tR\tdecidedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12;\n" +
	"\x04gate\x18\x06 \x01(\x0e2'.aether.platform.v1.common.ApprovalGateR\x04gate\x12!\n" +
	"\fcurrent_node\x18\a \x01(\tR\vcurrentNode\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\tR\texpiresAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x05R\aversion\"\x9d\x02\n" +
	"\x0fApprovalNodeRun\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12?\n" +
	"\x04mode\x18\x02 \x01(\x0e2+.aether.platform.v1.common.ApprovalNodeModeR\x04mode\x12#\n" +
	"\rdecided_count\x18\x03 \x01(\x05R\fdecidedCount\x12%\n" +
	"\x0erequired_count\x18\x04 \x01(\x05R\rrequiredCount\x12E\n" +
	"\x06status\x18\x05 \x01(\x0e2-.aether.platform.v1.common.ApprovalNodeStatusR\x06status\x12\x1d\n" +
	"\n" +
	"timeout_at\x18\x06 \x01(\tR\ttimeoutAt\"\xbb\x01\n" +
	"\x16ApprovalDecisionRecord\x12\x1f\n" +
	"\vapprover_id\x18\x01 \x01(\tR\n" +
	"approverId\x12G\n" +
	"\bdecision\x18\x02 \x01(\x0e2+.aether.platform.v1.common.ApprovalDecisionR\bdecision\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"decided_at\x18\x04 \x01(\tR\tdecidedAt\"\xbe\x04\n" +
	"\x14CreateRequestRequest\x12&\n" +
	"\x0fcatalog_item_id\x18\x01 \x01(\tR\rcatalogItemId\x12\x15\n" +
	"\x06env_id\x18\x02 \x01(\tR\x05envId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbundle_id\x18\x05 \x01(\tR\bbundleId\x12c\n" +
	"\vform_values\x18\x06 \x03(\v2B.aether.platform.v1.lifecycle.CreateRequestRequest.FormValuesEntryR\n" +
	"formValues\x12@\n" +
	"\x06source\x18\a \x01(\x0e2(.aether.platform.v1.common.RequestSourceR\x06source\x12l\n" +
	"\x0esource_context\x18\b \x03(\v2E.aether.platform.v1.lifecycle.CreateRequestRequest.SourceContextEntryR\rsourceContext\x1a=\n" +
	"\x0fFormValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12SourceContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x15CreateRequestResponse\x12H\n" +
	"\arequest\x18\x01 \x01(\v2..aether.platform.v1.lifecycle.LifecycleRequestR\arequest\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"2\n" +
	"\x11GetRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x85\x01\n" +
	"\x12GetRequestResponse\x12H\n" +
	"\arequest\x18\x01 \x01(\v2..aether.platform.v1.lifecycle.LifecycleRequestR\arequest\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"u\n" +
	"\x18ListRequestEventsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xb0\x01\n" +
	"\x19ListRequestEventsResponse\x12D\n" +
	"\x06events\x18\x01 \x03(\v2,.aether.platform.v1.lifecycle.LifecycleEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"x\n" +
	"\x14CancelRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x05R\x0fexpectedVersion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x88\x01\n" +
	"\x15CancelRequestResponse\x12H\n" +
	"\arequest\x18\x01 \x01(\v2..aether.platform.v1.lifecycle.LifecycleRequestR\arequest\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"1\n" +
	"\x10StartPlanRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x84\x01\n" +
	"\x11StartPlanResponse\x12H\n" +
	"\arequest\x18\x01 \x01(\v2..aether.platform.v1.lifecycle.LifecycleRequestR\arequest\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"\x84\x01\n" +
	"\x13GetArtifactResponse\x12F\n" +
	"\bartifact\x18\x01 \x01(\v2*.aether.platform.v1.lifecycle.PlanArtifactR\bartifact\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"4\n" +
	"\x13EvaluateGateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xb4\x01\n" +
	"\x14EvaluateGateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12>\n" +
	"\x05gates\x18\x03 \x03(\v2(.aether.platform.v1.lifecycle.GateResultR\x05gates\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xc3\x01\n" +
	"\x15DecideApprovalRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12G\n" +
	"\bdecision\x18\x02 \x01(\x0e2+.aether.platform.v1.common.ApprovalDecisionR\bdecision\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x120\n" +
	"\x14expected_run_version\x18\x04 \x01(\x05R\x12expectedRunVersion\"|\n" +
	"\x16DecideApprovalResponse\x12;\n" +
	"\x03run\x18\x01 \x01(\v2).aether.platform.v1.lifecycle.ApprovalRunR\x03run\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"2\n" +
	"\x11StartApplyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\";\n" +
	"\x12StartApplyResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\"\x84\x02\n" +
	"\x13ListRequestsRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12M\n" +
	"\rstatus_filter\x18\x03 \x03(\x0e2(.aether.platform.v1.common.RequestStatusR\fstatusFilter\x12&\n" +
	"\x0fcatalog_item_id\x18\x04 \x01(\tR\rcatalogItemId\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\xb1\x01\n" +
	"\x14ListRequestsResponse\x12J\n" +
	"\brequests\x18\x01 \x03(\v2..aether.platform.v1.lifecycle.LifecycleRequestR\brequests\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\xdd\x01\n" +
	"\x1bListPendingApprovalsRequest\x12\x1f\n" +
	"\vapprover_id\x18\x01 \x01(\tR\n" +
	"approverId\x12H\n" +
	"\vgate_filter\x18\x02 \x01(\x0e2'.aether.platform.v1.common.ApprovalGateR\n" +
	"gateFilter\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\xac\x01\n" +
	"\x1cListPendingApprovalsResponse\x12=\n" +
	"\x04runs\x18\x01 \x03(\v2).aether.platform.v1.lifecycle.ApprovalRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\".\n" +
	"\x15GetApprovalRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x95\x02\n" +
	"\x16GetApprovalRunResponse\x12;\n" +
	"\x03run\x18\x01 \x01(\v2).aether.platform.v1.lifecycle.ApprovalRunR\x03run\x12C\n" +
	"\x05nodes\x18\x02 \x03(\v2-.aether.platform.v1.lifecycle.ApprovalNodeRunR\x05nodes\x12R\n" +
	"\tdecisions\x18\x03 \x03(\v24.aether.platform.v1.lifecycle.ApprovalDecisionRecordR\tdecisions\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationIdB`Z^github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/lifecycle;lifecyclev1b\x06proto3"

var (
	file_platform_v1_lifecycle_dto_proto_rawDescOnce sync.Once
	file_platform_v1_lifecycle_dto_proto_rawDescData []byte
)

func file_platform_v1_lifecycle_dto_proto_rawDescGZIP() []byte {
	file_platform_v1_lifecycle_dto_proto_rawDescOnce.Do(func() {
		file_platform_v1_lifecycle_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_lifecycle_dto_proto_rawDesc), len(file_platform_v1_lifecycle_dto_proto_rawDesc)))
	})
	return file_platform_v1_lifecycle_dto_proto_rawDescData
}

var file_platform_v1_lifecycle_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_platform_v1_lifecycle_dto_proto_goTypes = []any{
	(*LifecycleRequest)(nil),             // 0: aether.platform.v1.lifecycle.LifecycleRequest
	(*LifecycleEvent)(nil),               // 1: aether.platform.v1.lifecycle.LifecycleEvent
	(*PlanArtifact)(nil),                 // 2: aether.platform.v1.lifecycle.PlanArtifact
	(*PlanSummary)(nil),                  // 3: aether.platform.v1.lifecycle.PlanSummary
	(*GateResult)(nil),                   // 4: aether.platform.v1.lifecycle.GateResult
	(*ApprovalRun)(nil),                  // 5: aether.platform.v1.lifecycle.ApprovalRun
	(*ApprovalNodeRun)(nil),              // 6: aether.platform.v1.lifecycle.ApprovalNodeRun
	(*ApprovalDecisionRecord)(nil),       // 7: aether.platform.v1.lifecycle.ApprovalDecisionRecord
	(*CreateRequestRequest)(nil),         // 8: aether.platform.v1.lifecycle.CreateRequestRequest
	(*CreateRequestResponse)(nil),        // 9: aether.platform.v1.lifecycle.CreateRequestResponse
	(*GetRequestRequest)(nil),            // 10: aether.platform.v1.lifecycle.GetRequestRequest
	(*GetRequestResponse)(nil),           // 11: aether.platform.v1.lifecycle.GetRequestResponse
	(*ListRequestEventsRequest)(nil),     // 12: aether.platform.v1.lifecycle.ListRequestEventsRequest
	(*ListRequestEventsResponse)(nil),    // 13: aether.platform.v1.lifecycle.ListRequestEventsResponse
	(*CancelRequestRequest)(nil),         // 14: aether.platform.v1.lifecycle.CancelRequestRequest
	(*CancelRequestResponse)(nil),        // 15: aether.platform.v1.lifecycle.CancelRequestResponse
	(*StartPlanRequest)(nil),             // 16: aether.platform.v1.lifecycle.StartPlanRequest
	(*StartPlanResponse)(nil),            // 17: aether.platform.v1.lifecycle.StartPlanResponse
	(*GetArtifactRequest)(nil),           // 18: aether.platform.v1.lifecycle.GetArtifactRequest
	(*GetArtifactResponse)(nil),          // 19: aether.platform.v1.lifecycle.GetArtifactResponse
	(*EvaluateGateRequest)(nil),          // 20: aether.platform.v1.lifecycle.EvaluateGateRequest
	(*EvaluateGateResponse)(nil),         // 21: aether.platform.v1.lifecycle.EvaluateGateResponse
	(*DecideApprovalRequest)(nil),        // 22: aether.platform.v1.lifecycle.DecideApprovalRequest
	(*DecideApprovalResponse)(nil),       // 23: aether.platform.v1.lifecycle.DecideApprovalResponse
	(*StartApplyRequest)(nil),            // 24: aether.platform.v1.lifecycle.StartApplyRequest
	(*StartApplyResponse)(nil),           // 25: aether.platform.v1.lifecycle.StartApplyResponse
	(*ListRequestsRequest)(nil),          // 26: aether.platform.v1.lifecycle.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 27: aether.platform.v1.lifecycle.ListRequestsResponse
	(*ListPendingApprovalsRequest)(nil),  // 28: aether.platform.v1.lifecycle.ListPendingApprovalsRequest
	(*ListPendingApprovalsResponse)(nil), // 29: aether.platform.v1.lifecycle.ListPendingApprovalsResponse
	(*GetApprovalRunRequest)(nil),        // 30: aether.platform.v1.lifecycle.GetApprovalRunRequest
	(*GetApprovalRunResponse)(nil),       // 31: aether.platform.v1.lifecycle.GetApprovalRunResponse
	nil,                                  // 32: aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntry
	nil,                                  // 33: aether.platform.v1.lifecycle.CreateRequestRequest.FormValuesEntry
	nil,                                  // 34: aether.platform.v1.lifecycle.CreateRequestRequest.SourceContextEntry
	(common.RequestStatus)(0),            // 35: aether.platform.v1.common.RequestStatus
	(common.RequestSource)(0),            // 36: aether.platform.v1.common.RequestSource
	(*common.Actor)(nil),                 // 37: aether.platform.v1.common.Actor
	(common.ArtifactStatus)(0),           // 38: aether.platform.v1.common.ArtifactStatus
	(common.GateSeverity)(0),             // 39: aether.platform.v1.common.GateSeverity
	(common.ApprovalRunStatus)(0),        // 40: aether.platform.v1.common.ApprovalRunStatus
	(common.ApprovalGate)(0),             // 41: aether.platform.v1.common.ApprovalGate
	(common.ApprovalNodeMode)(0),         // 42: aether.platform.v1.common.ApprovalNodeMode
	(common.ApprovalNodeStatus)(0),       // 43: aether.platform.v1.common.ApprovalNodeStatus
	(common.ApprovalDecision)(0),         // 44: aether.platform.v1.common.ApprovalDecision
}
var file_platform_v1_lifecycle_dto_proto_depIdxs = []int32{
	35, // 0: aether.platform.v1.lifecycle.LifecycleRequest.status:type_name -> aether.platform.v1.common.RequestStatus
	32, // 1: aether.platform.v1.lifecycle.LifecycleRequest.form_values:type_name -> aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntry
	36, // 2: aether.platform.v1.lifecycle.LifecycleRequest.source:type_name -> aether.platform.v1.common.RequestSource
	37, // 3: aether.platform.v1.lifecycle.LifecycleEvent.actor:type_name -> aether.platform.v1.common.Actor
	38, // 4: aether.platform.v1.lifecycle.PlanArtifact.status:type_name -> aether.platform.v1.common.ArtifactStatus
	3,  // 5: aether.platform.v1.lifecycle.PlanArtifact.summary:type_name -> aether.platform.v1.lifecycle.PlanSummary
	39, // 6: aether.platform.v1.lifecycle.GateResult.severity:type_name -> aether.platform.v1.common.GateSeverity
	40, // 7: aether.platform.v1.lifecycle.ApprovalRun.status:type_name -> aether.platform.v1.common.ApprovalRunStatus
	41, // 8: aether.platform.v1.lifecycle.ApprovalRun.gate:type_name -> aether.platform.v1.common.ApprovalGate
	42, // 9: aether.platform.v1.lifecycle.ApprovalNodeRun.mode:type_name -> aether.platform.v1.common.ApprovalNodeMode
	43, // 10: aether.platform.v1.lifecycle.ApprovalNodeRun.status:type_name -> aether.platform.v1.common.ApprovalNodeStatus
	44, // 11: aether.platform.v1.lifecycle.ApprovalDecisionRecord.decision:type_name -> aether.platform.v1.common.ApprovalDecision
	33, // 12: aether.platform.v1.lifecycle.CreateRequestRequest.form_values:type_name -> aether.platform.v1.lifecycle.CreateRequestRequest.FormValuesEntry
	36, // 13: aether.platform.v1.lifecycle.CreateRequestRequest.source:type_name -> aether.platform.v1.common.RequestSource
	34, // 14: aether.platform.v1.lifecycle.CreateRequestRequest.source_context:type_name -> aether.platform.v1.lifecycle.CreateRequestRequest.SourceContextEntry
	0,  // 15: aether.platform.v1.lifecycle.CreateRequestResponse.request:type_name -> aether.platform.v1.lifecycle.LifecycleRequest
	0,  // 16: aether.platform.v1.lifecycle.GetRequestResponse.request:type_name -> aether.platform.v1.lifecycle.LifecycleRequest
	1,  // 17: aether.platform.v1.lifecycle.ListRequestEventsResponse.events:type_name -> aether.platform.v1.lifecycle.LifecycleEvent
	0,  // 18: aether.platform.v1.lifecycle.CancelRequestResponse.request:type_name -> aether.platform.v1.lifecycle.LifecycleRequest
	0,  // 19: aether.platform.v1.lifecycle.StartPlanResponse.request:type_name -> aether.platform.v1.lifecycle.LifecycleRequest
	2,  // 20: aether.platform.v1.lifecycle.GetArtifactResponse.artifact:type_name -> aether.platform.v1.lifecycle.PlanArtifact
	4,  // 21: aether.platform.v1.lifecycle.EvaluateGateResponse.gates:type_name -> aether.platform.v1.lifecycle.GateResult
	44, // 22: aether.platform.v1.lifecycle.DecideApprovalRequest.decision:type_name -> aether.platform.v1.common.ApprovalDecision
	5,  // 23: aether.platform.v1.lifecycle.DecideApprovalResponse.run:type_name -> aether.platform.v1.lifecycle.ApprovalRun
	35, // 24: aether.platform.v1.lifecycle.ListRequestsRequest.status_filter:type_name -> aether.platform.v1.common.RequestStatus
	0,  // 25: aether.platform.v1.lifecycle.ListRequestsResponse.requests:type_name -> aether.platform.v1.lifecycle.LifecycleRequest
	41, // 26: aether.platform.v1.lifecycle.ListPendingApprovalsRequest.gate_filter:type_name -> aether.platform.v1.common.ApprovalGate
	5,  // 27: aether.platform.v1.lifecycle.ListPendingApprovalsResponse.runs:type_name -> aether.platform.v1.lifecycle.ApprovalRun
	5,  // 28: aether.platform.v1.lifecycle.GetApprovalRunResponse.run:type_name -> aether.platform.v1.lifecycle.ApprovalRun
	6,  // 29: aether.platform.v1.lifecycle.GetApprovalRunResponse.nodes:type_name -> aether.platform.v1.lifecycle.ApprovalNodeRun
	7,  // 30: aether.platform.v1.lifecycle.GetApprovalRunResponse.decisions:type_name -> aether.platform.v1.lifecycle.ApprovalDecisionRecord
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_platform_v1_lifecycle_dto_proto_init() }
func file_platform_v1_lifecycle_dto_proto_init() {
	if File_platform_v1_lifecycle_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_lifecycle_dto_proto_rawDesc), len(file_platform_v1_lifecycle_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_lifecycle_dto_proto_goTypes,
		DependencyIndexes: file_platform_v1_lifecycle_dto_proto_depIdxs,
		MessageInfos:      file_platform_v1_lifecycle_dto_proto_msgTypes,
	}.Build()
	File_platform_v1_lifecycle_dto_proto = out.File
	file_platform_v1_lifecycle_dto_proto_goTypes = nil
	file_platform_v1_lifecycle_dto_proto_depIdxs = nil
}
