// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/lifecycle/dto.proto

package lifecyclev1

import (
	common "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // req_<alphanum>
	Status            common.RequestStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=aether.platform.v1.common.RequestStatus" json:"status,omitempty"`
	CatalogItemId     string                 `protobuf:"bytes,3,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"` // cat_<alphanum>
	EnvId             string                 `protobuf:"bytes,4,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,5,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // team_<alphanum>
	TenantId          string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BundleId          string                 `protobuf:"bytes,7,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	FormValues        map[string]string      `protobuf:"bytes,8,rep,name=form_values,json=formValues,proto3" json:"form_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FormHash          string                 `protobuf:"bytes,9,opt,name=form_hash,json=formHash,proto3" json:"form_hash,omitempty"` // sha256:<hex>
	Source            common.RequestSource   `protobuf:"varint,10,opt,name=source,proto3,enum=aether.platform.v1.common.RequestSource" json:"source,omitempty"`
	PinnedCommit      string                 `protobuf:"bytes,11,opt,name=pinned_commit,json=pinnedCommit,proto3" json:"pinned_commit,omitempty"`         // sha256:<hex>
	PlanArtifactId    string                 `protobuf:"bytes,12,opt,name=plan_artifact_id,json=planArtifactId,proto3" json:"plan_artifact_id,omitempty"` // art_<alphanum>
	CostEstimateCents int64                  `protobuf:"varint,13,opt,name=cost_estimate_cents,json=costEstimateCents,proto3" json:"cost_estimate_cents,omitempty"`
	CostCurrency      string                 `protobuf:"bytes,14,opt,name=cost_currency,json=costCurrency,proto3" json:"cost_currency,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version           int32                  `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,18,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LifecycleRequest) Reset() {
	*x = LifecycleRequest{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleRequest) ProtoMessage() {}

func (x *LifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleRequest.ProtoReflect.Descriptor instead.
func (*LifecycleRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LifecycleRequest) GetStatus() common.RequestStatus {
	if x != nil {
		return x.Status
	}
	return common.RequestStatus(0)
}

func (x *LifecycleRequest) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *LifecycleRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *LifecycleRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *LifecycleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LifecycleRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *LifecycleRequest) GetFormValues() map[string]string {
	if x != nil {
		return x.FormValues
	}
	return nil
}

func (x *LifecycleRequest) GetFormHash() string {
	if x != nil {
		return x.FormHash
	}
	return ""
}

func (x *LifecycleRequest) GetSource() common.RequestSource {
	if x != nil {
		return x.Source
	}
	return common.RequestSource(0)
}

func (x *LifecycleRequest) GetPinnedCommit() string {
	if x != nil {
		return x.PinnedCommit
	}
	return ""
}

func (x *LifecycleRequest) GetPlanArtifactId() string {
	if x != nil {
		return x.PlanArtifactId
	}
	return ""
}

func (x *LifecycleRequest) GetCostEstimateCents() int64 {
	if x != nil {
		return x.CostEstimateCents
	}
	return 0
}

func (x *LifecycleRequest) GetCostCurrency() string {
	if x != nil {
		return x.CostCurrency
	}
	return ""
}

func (x *LifecycleRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LifecycleRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *LifecycleRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LifecycleRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type LifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // evt_<alphanum>
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Actor         *common.Actor          `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{1}
}

func (x *LifecycleEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LifecycleEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LifecycleEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LifecycleEvent) GetActor() *common.Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *LifecycleEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *LifecycleEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type PlanArtifact struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // art_<alphanum>
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status            common.ArtifactStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=aether.platform.v1.common.ArtifactStatus" json:"status,omitempty"`
	PlanHash          string                 `protobuf:"bytes,4,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"` // sha256:<hex>
	Summary           *PlanSummary           `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CostEstimateCents int64                  `protobuf:"varint,6,opt,name=cost_estimate_cents,json=costEstimateCents,proto3" json:"cost_estimate_cents,omitempty"`
	StorageUri        string                 `protobuf:"bytes,7,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ExpiresAt         string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanArtifact) Reset() {
	*x = PlanArtifact{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanArtifact) ProtoMessage() {}

func (x *PlanArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanArtifact.ProtoReflect.Descriptor instead.
func (*PlanArtifact) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{2}
}

func (x *PlanArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanArtifact) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlanArtifact) GetStatus() common.ArtifactStatus {
	if x != nil {
		return x.Status
	}
	return common.ArtifactStatus(0)
}

func (x *PlanArtifact) GetPlanHash() string {
	if x != nil {
		return x.PlanHash
	}
	return ""
}

func (x *PlanArtifact) GetSummary() *PlanSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *PlanArtifact) GetCostEstimateCents() int64 {
	if x != nil {
		return x.CostEstimateCents
	}
	return 0
}

func (x *PlanArtifact) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *PlanArtifact) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PlanArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PlanSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourcesToAdd     int32                  `protobuf:"varint,1,opt,name=resources_to_add,json=resourcesToAdd,proto3" json:"resources_to_add,omitempty"`
	ResourcesToChange  int32                  `protobuf:"varint,2,opt,name=resources_to_change,json=resourcesToChange,proto3" json:"resources_to_change,omitempty"`
	ResourcesToDestroy int32                  `protobuf:"varint,3,opt,name=resources_to_destroy,json=resourcesToDestroy,proto3" json:"resources_to_destroy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlanSummary) Reset() {
	*x = PlanSummary{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanSummary) ProtoMessage() {}

func (x *PlanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanSummary.ProtoReflect.Descriptor instead.
func (*PlanSummary) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{3}
}

func (x *PlanSummary) GetResourcesToAdd() int32 {
	if x != nil {
		return x.ResourcesToAdd
	}
	return 0
}

func (x *PlanSummary) GetResourcesToChange() int32 {
	if x != nil {
		return x.ResourcesToChange
	}
	return 0
}

func (x *PlanSummary) GetResourcesToDestroy() int32 {
	if x != nil {
		return x.ResourcesToDestroy
	}
	return 0
}

type GateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GateId        string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Policy        string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Severity      common.GateSeverity    `protobuf:"varint,5,opt,name=severity,proto3,enum=aether.platform.v1.common.GateSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResult) Reset() {
	*x = GateResult{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResult) ProtoMessage() {}

func (x *GateResult) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResult.ProtoReflect.Descriptor instead.
func (*GateResult) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{4}
}

func (x *GateResult) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GateResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *GateResult) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *GateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GateResult) GetSeverity() common.GateSeverity {
	if x != nil {
		return x.Severity
	}
	return common.GateSeverity(0)
}

type ApprovalRun struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RunId         string                   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // run_<alphanum>
	Status        common.ApprovalRunStatus `protobuf:"varint,2,opt,name=status,proto3,enum=aether.platform.v1.common.ApprovalRunStatus" json:"status,omitempty"`
	DecidedBy     string                   `protobuf:"bytes,3,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	DecidedAt     string                   `protobuf:"bytes,4,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRun) Reset() {
	*x = ApprovalRun{}
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRun) ProtoMessage() {}

func (x *ApprovalRun) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_lifecycle_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRun.ProtoReflect.Descriptor instead.
func (*ApprovalRun) Descriptor() ([]byte, []int) {
	return file_platform_v1_lifecycle_dto_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApprovalRun) GetStatus() common.ApprovalRunStatus {
	if x != nil {
		return x.Status
	}
	return common.ApprovalRunStatus(0)
}

func (x *ApprovalRun) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *ApprovalRun) GetDecidedAt() string {
	if x != nil {
		return x.DecidedAt
	}
	return ""
}

var File_platform_v1_lifecycle_dto_proto protoreflect.FileDescriptor

const file_platform_v1_lifecycle_dto_proto_rawDesc = "" +
	"\n" +
	"\x1fplatform/v1/lifecycle/dto.proto\x12\x1caether.platform.v1.lifecycle\x1a\x1cplatform/v1/common/dto.proto\x1a\x1dplatform/v1/common/enum.proto\"\x98\x06\n" +
	"\x10LifecycleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\x06status\x18\x02 \x01(\x0e2(.aether.platform.v1.common.RequestStatusR\x06status\x12&\n" +
	"\x0fcatalog_item_id\x18\x03 \x01(\tR\rcatalogItemId\x12\x15\n" +
	"\x06env_id\x18\x04 \x01(\tR\x05envId\x12\x17\n" +
	"\ateam_id\x18\x05 \x01(\tR\x06teamId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12\x1b\n" +
	"\tbundle_id\x18\a \x01(\tR\bbundleId\x12_\n" +
	"\vform_values\x18\b \x03(\v2>.aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntryR\n" +
	"formValues\x12\x1b\n" +
	"\tform_hash\x18\t \x01(\tR\bformHash\x12@\n" +
	"\x06source\x18\n" +
	" \x01(\x0e2(.aether.platform.v1.common.RequestSourceR\x06source\x12#\n" +
	"\rpinned_commit\x18\v \x01(\tR\fpinnedCommit\x12(\n" +
	"\x10plan_artifact_id\x18\f \x01(\tR\x0eplanArtifactId\x12.\n" +
	"\x13cost_estimate_cents\x18\r \x01(\x03R\x11costEstimateCents\x12#\n" +
	"\rcost_currency\x18\x0e \x01(\tR\fcostCurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x05R\aversion\x12%\n" +
	"\x0ecorrelation_id\x18\x12 \x01(\tR\rcorrelationId\x1a=\n" +
	"\x0fFormValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x0eLifecycleEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x126\n" +
	"\x05actor\x18\x04 \x01(\v2 .aether.platform.v1.common.ActorR\x05actor\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\"\xf1\x02\n" +
	"\fPlanArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).aether.platform.v1.common.ArtifactStatusR\x06status\x12\x1b\n" +
	"\tplan_hash\x18\x04 \x01(\tR\bplanHash\x12C\n" +
	"\asummary\x18\x05 \x01(\v2).aether.platform.v1.lifecycle.PlanSummaryR\asummary\x12.\n" +
	"\x13cost_estimate_cents\x18\x06 \x01(\x03R\x11costEstimateCents\x12\x1f\n" +
	"\vstorage_uri\x18\a \x01(\tR\n" +
	"storageUri\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x99\x01\n" +
	"\vPlanSummary\x12(\n" +
	"\x10resources_to_add\x18\x01 \x01(\x05R\x0eresourcesToAdd\x12.\n" +
	"\x13resources_to_change\x18\x02 \x01(\x05R\x11resourcesToChange\x120\n" +
	"\x14resources_to_destroy\x18\x03 \x01(\x05R\x12resourcesToDestroy\"\xb4\x01\n" +
	"\n" +
	"GateResult\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12C\n" +
	"\bseverity\x18\x05 \x01(\x0e2'.aether.platform.v1.common.GateSeverityR\bseverity\"\xa8\x01\n" +
	"\vApprovalRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12D\n" +
	"\x06status\x18\x02 \x01(\x0e2,.aether.platform.v1.common.ApprovalRunStatusR\x06status\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x03 \x01(\tR\tdecidedBy\x12\x1d\n" +
	"\n" +
	"decided_at\x18\x04 \x01(\tR\tdecidedAtB`Z^github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/lifecycle;lifecyclev1b\x06proto3"

var (
	file_platform_v1_lifecycle_dto_proto_rawDescOnce sync.Once
	file_platform_v1_lifecycle_dto_proto_rawDescData []byte
)

func file_platform_v1_lifecycle_dto_proto_rawDescGZIP() []byte {
	file_platform_v1_lifecycle_dto_proto_rawDescOnce.Do(func() {
		file_platform_v1_lifecycle_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_lifecycle_dto_proto_rawDesc), len(file_platform_v1_lifecycle_dto_proto_rawDesc)))
	})
	return file_platform_v1_lifecycle_dto_proto_rawDescData
}

var file_platform_v1_lifecycle_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_platform_v1_lifecycle_dto_proto_goTypes = []any{
	(*LifecycleRequest)(nil),      // 0: aether.platform.v1.lifecycle.LifecycleRequest
	(*LifecycleEvent)(nil),        // 1: aether.platform.v1.lifecycle.LifecycleEvent
	(*PlanArtifact)(nil),          // 2: aether.platform.v1.lifecycle.PlanArtifact
	(*PlanSummary)(nil),           // 3: aether.platform.v1.lifecycle.PlanSummary
	(*GateResult)(nil),            // 4: aether.platform.v1.lifecycle.GateResult
	(*ApprovalRun)(nil),           // 5: aether.platform.v1.lifecycle.ApprovalRun
	nil,                           // 6: aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntry
	(common.RequestStatus)(0),     // 7: aether.platform.v1.common.RequestStatus
	(common.RequestSource)(0),     // 8: aether.platform.v1.common.RequestSource
	(*common.Actor)(nil),          // 9: aether.platform.v1.common.Actor
	(common.ArtifactStatus)(0),    // 10: aether.platform.v1.common.ArtifactStatus
	(common.GateSeverity)(0),      // 11: aether.platform.v1.common.GateSeverity
	(common.ApprovalRunStatus)(0), // 12: aether.platform.v1.common.ApprovalRunStatus
}
var file_platform_v1_lifecycle_dto_proto_depIdxs = []int32{
	7,  // 0: aether.platform.v1.lifecycle.LifecycleRequest.status:type_name -> aether.platform.v1.common.RequestStatus
	6,  // 1: aether.platform.v1.lifecycle.LifecycleRequest.form_values:type_name -> aether.platform.v1.lifecycle.LifecycleRequest.FormValuesEntry
	8,  // 2: aether.platform.v1.lifecycle.LifecycleRequest.source:type_name -> aether.platform.v1.common.RequestSource
	9,  // 3: aether.platform.v1.lifecycle.LifecycleEvent.actor:type_name -> aether.platform.v1.common.Actor
	10, // 4: aether.platform.v1.lifecycle.PlanArtifact.status:type_name -> aether.platform.v1.common.ArtifactStatus
	3,  // 5: aether.platform.v1.lifecycle.PlanArtifact.summary:type_name -> aether.platform.v1.lifecycle.PlanSummary
	11, // 6: aether.platform.v1.lifecycle.GateResult.severity:type_name -> aether.platform.v1.common.GateSeverity
	12, // 7: aether.platform.v1.lifecycle.ApprovalRun.status:type_name -> aether.platform.v1.common.ApprovalRunStatus
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_platform_v1_lifecycle_dto_proto_init() }
func file_platform_v1_lifecycle_dto_proto_init() {
	if File_platform_v1_lifecycle_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_lifecycle_dto_proto_rawDesc), len(file_platform_v1_lifecycle_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_lifecycle_dto_proto_goTypes,
		DependencyIndexes: file_platform_v1_lifecycle_dto_proto_depIdxs,
		MessageInfos:      file_platform_v1_lifecycle_dto_proto_msgTypes,
	}.Build()
	File_platform_v1_lifecycle_dto_proto = out.File
	file_platform_v1_lifecycle_dto_proto_goTypes = nil
	file_platform_v1_lifecycle_dto_proto_depIdxs = nil
}
