// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/lifecycle/srv.proto

package lifecyclev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_platform_v1_lifecycle_srv_proto protoreflect.FileDescriptor

const file_platform_v1_lifecycle_srv_proto_rawDesc = "" +
	"\n" +
	"\x1fplatform/v1/lifecycle/srv.proto\x12\x1caether.platform.v1.lifecycle\x1a\x1fplatform/v1/lifecycle/dto.proto2\xd7\b\n" +
	"\x10LifecycleService\x12z\n" +
	"\rCreateRequest\x122.aether.platform.v1.lifecycle.CreateRequestRequest\x1a3.aether.platform.v1.lifecycle.CreateRequestResponse\"\x00\x12q\n" +
	"\n" +
	"GetRequest\x12/.aether.platform.v1.lifecycle.GetRequestRequest\x1a0.aether.platform.v1.lifecycle.GetRequestResponse\"\x00\x12\x86\x01\n" +
	"\x11ListRequestEvents\x126.aether.platform.v1.lifecycle.ListRequestEventsRequest\x1a7.aether.platform.v1.lifecycle.ListRequestEventsResponse\"\x00\x12z\n" +
	"\rCancelRequest\x122.aether.platform.v1.lifecycle.CancelRequestRequest\x1a3.aether.platform.v1.lifecycle.CancelRequestResponse\"\x00\x12n\n" +
	"\tStartPlan\x12..aether.platform.v1.lifecycle.StartPlanRequest\x1a/.aether.platform.v1.lifecycle.StartPlanResponse\"\x00\x12t\n" +
	"\vGetArtifact\x120.aether.platform.v1.lifecycle.GetArtifactRequest\x1a1.aether.platform.v1.lifecycle.GetArtifactResponse\"\x00\x12w\n" +
	"\fEvaluateGate\x121.aether.platform.v1.lifecycle.EvaluateGateRequest\x1a2.aether.platform.v1.lifecycle.EvaluateGateResponse\"\x00\x12}\n" +
	"\x0eDecideApproval\x123.aether.platform.v1.lifecycle.DecideApprovalRequest\x1a4.aether.platform.v1.lifecycle.DecideApprovalResponse\"\x00\x12q\n" +
	"\n" +
	"StartApply\x12/.aether.platform.v1.lifecycle.StartApplyRequest\x1a0.aether.platform.v1.lifecycle.StartApplyResponse\"\x00B`Z^github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/lifecycle;lifecyclev1b\x06proto3"

var file_platform_v1_lifecycle_srv_proto_goTypes = []any{
	(*CreateRequestRequest)(nil),      // 0: aether.platform.v1.lifecycle.CreateRequestRequest
	(*GetRequestRequest)(nil),         // 1: aether.platform.v1.lifecycle.GetRequestRequest
	(*ListRequestEventsRequest)(nil),  // 2: aether.platform.v1.lifecycle.ListRequestEventsRequest
	(*CancelRequestRequest)(nil),      // 3: aether.platform.v1.lifecycle.CancelRequestRequest
	(*StartPlanRequest)(nil),          // 4: aether.platform.v1.lifecycle.StartPlanRequest
	(*GetArtifactRequest)(nil),        // 5: aether.platform.v1.lifecycle.GetArtifactRequest
	(*EvaluateGateRequest)(nil),       // 6: aether.platform.v1.lifecycle.EvaluateGateRequest
	(*DecideApprovalRequest)(nil),     // 7: aether.platform.v1.lifecycle.DecideApprovalRequest
	(*StartApplyRequest)(nil),         // 8: aether.platform.v1.lifecycle.StartApplyRequest
	(*CreateRequestResponse)(nil),     // 9: aether.platform.v1.lifecycle.CreateRequestResponse
	(*GetRequestResponse)(nil),        // 10: aether.platform.v1.lifecycle.GetRequestResponse
	(*ListRequestEventsResponse)(nil), // 11: aether.platform.v1.lifecycle.ListRequestEventsResponse
	(*CancelRequestResponse)(nil),     // 12: aether.platform.v1.lifecycle.CancelRequestResponse
	(*StartPlanResponse)(nil),         // 13: aether.platform.v1.lifecycle.StartPlanResponse
	(*GetArtifactResponse)(nil),       // 14: aether.platform.v1.lifecycle.GetArtifactResponse
	(*EvaluateGateResponse)(nil),      // 15: aether.platform.v1.lifecycle.EvaluateGateResponse
	(*DecideApprovalResponse)(nil),    // 16: aether.platform.v1.lifecycle.DecideApprovalResponse
	(*StartApplyResponse)(nil),        // 17: aether.platform.v1.lifecycle.StartApplyResponse
}
var file_platform_v1_lifecycle_srv_proto_depIdxs = []int32{
	0,  // 0: aether.platform.v1.lifecycle.LifecycleService.CreateRequest:input_type -> aether.platform.v1.lifecycle.CreateRequestRequest
	1,  // 1: aether.platform.v1.lifecycle.LifecycleService.GetRequest:input_type -> aether.platform.v1.lifecycle.GetRequestRequest
	2,  // 2: aether.platform.v1.lifecycle.LifecycleService.ListRequestEvents:input_type -> aether.platform.v1.lifecycle.ListRequestEventsRequest
	3,  // 3: aether.platform.v1.lifecycle.LifecycleService.CancelRequest:input_type -> aether.platform.v1.lifecycle.CancelRequestRequest
	4,  // 4: aether.platform.v1.lifecycle.LifecycleService.StartPlan:input_type -> aether.platform.v1.lifecycle.StartPlanRequest
	5,  // 5: aether.platform.v1.lifecycle.LifecycleService.GetArtifact:input_type -> aether.platform.v1.lifecycle.GetArtifactRequest
	6,  // 6: aether.platform.v1.lifecycle.LifecycleService.EvaluateGate:input_type -> aether.platform.v1.lifecycle.EvaluateGateRequest
	7,  // 7: aether.platform.v1.lifecycle.LifecycleService.DecideApproval:input_type -> aether.platform.v1.lifecycle.DecideApprovalRequest
	8,  // 8: aether.platform.v1.lifecycle.LifecycleService.StartApply:input_type -> aether.platform.v1.lifecycle.StartApplyRequest
	9,  // 9: aether.platform.v1.lifecycle.LifecycleService.CreateRequest:output_type -> aether.platform.v1.lifecycle.CreateRequestResponse
	10, // 10: aether.platform.v1.lifecycle.LifecycleService.GetRequest:output_type -> aether.platform.v1.lifecycle.GetRequestResponse
	11, // 11: aether.platform.v1.lifecycle.LifecycleService.ListRequestEvents:output_type -> aether.platform.v1.lifecycle.ListRequestEventsResponse
	12, // 12: aether.platform.v1.lifecycle.LifecycleService.CancelRequest:output_type -> aether.platform.v1.lifecycle.CancelRequestResponse
	13, // 13: aether.platform.v1.lifecycle.LifecycleService.StartPlan:output_type -> aether.platform.v1.lifecycle.StartPlanResponse
	14, // 14: aether.platform.v1.lifecycle.LifecycleService.GetArtifact:output_type -> aether.platform.v1.lifecycle.GetArtifactResponse
	15, // 15: aether.platform.v1.lifecycle.LifecycleService.EvaluateGate:output_type -> aether.platform.v1.lifecycle.EvaluateGateResponse
	16, // 16: aether.platform.v1.lifecycle.LifecycleService.DecideApproval:output_type -> aether.platform.v1.lifecycle.DecideApprovalResponse
	17, // 17: aether.platform.v1.lifecycle.LifecycleService.StartApply:output_type -> aether.platform.v1.lifecycle.StartApplyResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_platform_v1_lifecycle_srv_proto_init() }
func file_platform_v1_lifecycle_srv_proto_init() {
	if File_platform_v1_lifecycle_srv_proto != nil {
		return
	}
	file_platform_v1_lifecycle_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_lifecycle_srv_proto_rawDesc), len(file_platform_v1_lifecycle_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_v1_lifecycle_srv_proto_goTypes,
		DependencyIndexes: file_platform_v1_lifecycle_srv_proto_depIdxs,
	}.Build()
	File_platform_v1_lifecycle_srv_proto = out.File
	file_platform_v1_lifecycle_srv_proto_goTypes = nil
	file_platform_v1_lifecycle_srv_proto_depIdxs = nil
}
