// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/registry/dto.proto

package registryv1

import (
	common "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	GitSource   string                 `protobuf:"bytes,4,opt,name=git_source,json=gitSource,proto3" json:"git_source,omitempty"`
	Provider    string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Status      common.ModuleStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=aether.platform.v1.common.ModuleStatus" json:"status,omitempty"`
	Versions    []*ModuleVersion       `protobuf:"bytes,7,rep,name=versions,proto3" json:"versions,omitempty"`
	CreatedAt   string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// module_path: subdir within the git repo (e.g. "atomic/rds"). Empty = root.
	// Maps to modules.module_path column (DB NOT NULL DEFAULT ”).
	ModulePath string `protobuf:"bytes,10,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	// owner_team_id: team responsible for this module. Maps to
	// modules.owner_team_id (DB NOT NULL). Required at registration.
	OwnerTeamId   string `protobuf:"bytes,11,opt,name=owner_team_id,json=ownerTeamId,proto3" json:"owner_team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetGitSource() string {
	if x != nil {
		return x.GitSource
	}
	return ""
}

func (x *Module) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Module) GetStatus() common.ModuleStatus {
	if x != nil {
		return x.Status
	}
	return common.ModuleStatus(0)
}

func (x *Module) GetVersions() []*ModuleVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *Module) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Module) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Module) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *Module) GetOwnerTeamId() string {
	if x != nil {
		return x.OwnerTeamId
	}
	return ""
}

type ModuleVersion struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CommitSha             string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Providers             []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	VariablesContractJson string                 `protobuf:"bytes,4,opt,name=variables_contract_json,json=variablesContractJson,proto3" json:"variables_contract_json,omitempty"`
	Dependencies          []*ModuleDependency    `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	RegisteredAt          string                 `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ModuleVersion) Reset() {
	*x = ModuleVersion{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleVersion) ProtoMessage() {}

func (x *ModuleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleVersion.ProtoReflect.Descriptor instead.
func (*ModuleVersion) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleVersion) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ModuleVersion) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ModuleVersion) GetVariablesContractJson() string {
	if x != nil {
		return x.VariablesContractJson
	}
	return ""
}

func (x *ModuleVersion) GetDependencies() []*ModuleDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ModuleVersion) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

// ModuleDependency is the provider-declared cross-layer dependency
// contract extracted from a module at registration time (D25 zero
// intrusion: the module declares outputs/variables; the platform reads
// them without modifying the module).
type ModuleDependency struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VariableName    string                 `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DependsOnLayer  string                 `protobuf:"bytes,3,opt,name=depends_on_layer,json=dependsOnLayer,proto3" json:"depends_on_layer,omitempty"`
	DependsOnModule string                 `protobuf:"bytes,4,opt,name=depends_on_module,json=dependsOnModule,proto3" json:"depends_on_module,omitempty"`
	OutputKey       string                 `protobuf:"bytes,5,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`
	Required        bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModuleDependency) Reset() {
	*x = ModuleDependency{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDependency) ProtoMessage() {}

func (x *ModuleDependency) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDependency.ProtoReflect.Descriptor instead.
func (*ModuleDependency) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleDependency) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *ModuleDependency) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleDependency) GetDependsOnLayer() string {
	if x != nil {
		return x.DependsOnLayer
	}
	return ""
}

func (x *ModuleDependency) GetDependsOnModule() string {
	if x != nil {
		return x.DependsOnModule
	}
	return ""
}

func (x *ModuleDependency) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *ModuleDependency) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type RegisterModuleRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	GitSource   string                 `protobuf:"bytes,1,opt,name=git_source,json=gitSource,proto3" json:"git_source,omitempty"`
	ModulePath  string                 `protobuf:"bytes,2,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	Version     string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Provider    string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Name        string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// owner_team_id: team that owns this module (DB NOT NULL). The caller
	// must be a member of this team or an admin.
	OwnerTeamId   string `protobuf:"bytes,7,opt,name=owner_team_id,json=ownerTeamId,proto3" json:"owner_team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModuleRequest) Reset() {
	*x = RegisterModuleRequest{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleRequest) ProtoMessage() {}

func (x *RegisterModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterModuleRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterModuleRequest) GetGitSource() string {
	if x != nil {
		return x.GitSource
	}
	return ""
}

func (x *RegisterModuleRequest) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *RegisterModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterModuleRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterModuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterModuleRequest) GetOwnerTeamId() string {
	if x != nil {
		return x.OwnerTeamId
	}
	return ""
}

type RegisterModuleResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Module *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// module_version_id: snowflake ID of the freshly-created module_version.
	// Surfaced so the operator can immediately publish the version to the
	// catalog (PublishCatalogItem.module_version) without a separate lookup.
	ModuleVersionId string `protobuf:"bytes,2,opt,name=module_version_id,json=moduleVersionId,proto3" json:"module_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterModuleResponse) Reset() {
	*x = RegisterModuleResponse{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModuleResponse) ProtoMessage() {}

func (x *RegisterModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModuleResponse.ProtoReflect.Descriptor instead.
func (*RegisterModuleResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *RegisterModuleResponse) GetModuleVersionId() string {
	if x != nil {
		return x.ModuleVersionId
	}
	return ""
}

type ListModulesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *common.PageRequest    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ProviderFilter string                 `protobuf:"bytes,2,opt,name=provider_filter,json=providerFilter,proto3" json:"provider_filter,omitempty"`
	StatusFilter   common.ModuleStatus    `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=aether.platform.v1.common.ModuleStatus" json:"status_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{5}
}

func (x *ListModulesRequest) GetPagination() *common.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListModulesRequest) GetProviderFilter() string {
	if x != nil {
		return x.ProviderFilter
	}
	return ""
}

func (x *ListModulesRequest) GetStatusFilter() common.ModuleStatus {
	if x != nil {
		return x.StatusFilter
	}
	return common.ModuleStatus(0)
}

type ListModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	Pagination    *common.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesResponse) Reset() {
	*x = ListModulesResponse{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesResponse) ProtoMessage() {}

func (x *ListModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesResponse.ProtoReflect.Descriptor instead.
func (*ListModulesResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{6}
}

func (x *ListModulesResponse) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *ListModulesResponse) GetPagination() *common.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{7}
}

func (x *GetModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

type GetModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleResponse) Reset() {
	*x = GetModuleResponse{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleResponse) ProtoMessage() {}

func (x *GetModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleResponse.ProtoReflect.Descriptor instead.
func (*GetModuleResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{8}
}

func (x *GetModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

type DeprecateModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecateModuleRequest) Reset() {
	*x = DeprecateModuleRequest{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecateModuleRequest) ProtoMessage() {}

func (x *DeprecateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecateModuleRequest.ProtoReflect.Descriptor instead.
func (*DeprecateModuleRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{9}
}

func (x *DeprecateModuleRequest) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *DeprecateModuleRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeprecateModuleRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeprecateModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        *Module                `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeprecateModuleResponse) Reset() {
	*x = DeprecateModuleResponse{}
	mi := &file_platform_v1_registry_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeprecateModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeprecateModuleResponse) ProtoMessage() {}

func (x *DeprecateModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_registry_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeprecateModuleResponse.ProtoReflect.Descriptor instead.
func (*DeprecateModuleResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_registry_dto_proto_rawDescGZIP(), []int{10}
}

func (x *DeprecateModuleResponse) GetModule() *Module {
	if x != nil {
		return x.Module
	}
	return nil
}

var File_platform_v1_registry_dto_proto protoreflect.FileDescriptor

const file_platform_v1_registry_dto_proto_rawDesc = "" +
	"\n" +
	"\x1eplatform/v1/registry/dto.proto\x12\x1baether.platform.v1.registry\x1a\x1cplatform/v1/common/dto.proto\x1a\x1dplatform/v1/common/enum.proto\"\x95\x03\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"git_source\x18\x04 \x01(\tR\tgitSource\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12?\n" +
	"\x06status\x18\x06 \x01(\x0e2'.aether.platform.v1.common.ModuleStatusR\x06status\x12F\n" +
	"\bversions\x18\a \x03(\v2*.aether.platform.v1.registry.ModuleVersionR\bversions\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vmodule_path\x18\n" +
	" \x01(\tR\n" +
	"modulePath\x12\"\n" +
	"\rowner_team_id\x18\v \x01(\tR\vownerTeamId\"\x96\x02\n" +
	"\rModuleVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x126\n" +
	"\x17variables_contract_json\x18\x04 \x01(\tR\x15variablesContractJson\x12Q\n" +
	"\fdependencies\x18\x05 \x03(\v2-.aether.platform.v1.registry.ModuleDependencyR\fdependencies\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\tR\fregisteredAt\"\xea\x01\n" +
	"\x10ModuleDependency\x12#\n" +
	"\rvariable_name\x18\x01 \x01(\tR\fvariableName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10depends_on_layer\x18\x03 \x01(\tR\x0edependsOnLayer\x12*\n" +
	"\x11depends_on_module\x18\x04 \x01(\tR\x0fdependsOnModule\x12\x1d\n" +
	"\n" +
	"output_key\x18\x05 \x01(\tR\toutputKey\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\"\xe7\x01\n" +
	"\x15RegisterModuleRequest\x12\x1d\n" +
	"\n" +
	"git_source\x18\x01 \x01(\tR\tgitSource\x12\x1f\n" +
	"\vmodule_path\x18\x02 \x01(\tR\n" +
	"modulePath\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\"\n" +
	"\rowner_team_id\x18\a \x01(\tR\vownerTeamId\"\x81\x01\n" +
	"\x16RegisterModuleResponse\x12;\n" +
	"\x06module\x18\x01 \x01(\v2#.aether.platform.v1.registry.ModuleR\x06module\x12*\n" +
	"\x11module_version_id\x18\x02 \x01(\tR\x0fmoduleVersionId\"\xd3\x01\n" +
	"\x12ListModulesRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.aether.platform.v1.common.PageRequestR\n" +
	"pagination\x12'\n" +
	"\x0fprovider_filter\x18\x02 \x01(\tR\x0eproviderFilter\x12L\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2'.aether.platform.v1.common.ModuleStatusR\fstatusFilter\"\x9d\x01\n" +
	"\x13ListModulesResponse\x12=\n" +
	"\amodules\x18\x01 \x03(\v2#.aether.platform.v1.registry.ModuleR\amodules\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.aether.platform.v1.common.PageResponseR\n" +
	"pagination\"/\n" +
	"\x10GetModuleRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\"P\n" +
	"\x11GetModuleResponse\x12;\n" +
	"\x06module\x18\x01 \x01(\v2#.aether.platform.v1.registry.ModuleR\x06module\"g\n" +
	"\x16DeprecateModuleRequest\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"V\n" +
	"\x17DeprecateModuleResponse\x12;\n" +
	"\x06module\x18\x01 \x01(\v2#.aether.platform.v1.registry.ModuleR\x06moduleB^Z\\github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/registry;registryv1b\x06proto3"

var (
	file_platform_v1_registry_dto_proto_rawDescOnce sync.Once
	file_platform_v1_registry_dto_proto_rawDescData []byte
)

func file_platform_v1_registry_dto_proto_rawDescGZIP() []byte {
	file_platform_v1_registry_dto_proto_rawDescOnce.Do(func() {
		file_platform_v1_registry_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_registry_dto_proto_rawDesc), len(file_platform_v1_registry_dto_proto_rawDesc)))
	})
	return file_platform_v1_registry_dto_proto_rawDescData
}

var file_platform_v1_registry_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_platform_v1_registry_dto_proto_goTypes = []any{
	(*Module)(nil),                  // 0: aether.platform.v1.registry.Module
	(*ModuleVersion)(nil),           // 1: aether.platform.v1.registry.ModuleVersion
	(*ModuleDependency)(nil),        // 2: aether.platform.v1.registry.ModuleDependency
	(*RegisterModuleRequest)(nil),   // 3: aether.platform.v1.registry.RegisterModuleRequest
	(*RegisterModuleResponse)(nil),  // 4: aether.platform.v1.registry.RegisterModuleResponse
	(*ListModulesRequest)(nil),      // 5: aether.platform.v1.registry.ListModulesRequest
	(*ListModulesResponse)(nil),     // 6: aether.platform.v1.registry.ListModulesResponse
	(*GetModuleRequest)(nil),        // 7: aether.platform.v1.registry.GetModuleRequest
	(*GetModuleResponse)(nil),       // 8: aether.platform.v1.registry.GetModuleResponse
	(*DeprecateModuleRequest)(nil),  // 9: aether.platform.v1.registry.DeprecateModuleRequest
	(*DeprecateModuleResponse)(nil), // 10: aether.platform.v1.registry.DeprecateModuleResponse
	(common.ModuleStatus)(0),        // 11: aether.platform.v1.common.ModuleStatus
	(*common.PageRequest)(nil),      // 12: aether.platform.v1.common.PageRequest
	(*common.PageResponse)(nil),     // 13: aether.platform.v1.common.PageResponse
}
var file_platform_v1_registry_dto_proto_depIdxs = []int32{
	11, // 0: aether.platform.v1.registry.Module.status:type_name -> aether.platform.v1.common.ModuleStatus
	1,  // 1: aether.platform.v1.registry.Module.versions:type_name -> aether.platform.v1.registry.ModuleVersion
	2,  // 2: aether.platform.v1.registry.ModuleVersion.dependencies:type_name -> aether.platform.v1.registry.ModuleDependency
	0,  // 3: aether.platform.v1.registry.RegisterModuleResponse.module:type_name -> aether.platform.v1.registry.Module
	12, // 4: aether.platform.v1.registry.ListModulesRequest.pagination:type_name -> aether.platform.v1.common.PageRequest
	11, // 5: aether.platform.v1.registry.ListModulesRequest.status_filter:type_name -> aether.platform.v1.common.ModuleStatus
	0,  // 6: aether.platform.v1.registry.ListModulesResponse.modules:type_name -> aether.platform.v1.registry.Module
	13, // 7: aether.platform.v1.registry.ListModulesResponse.pagination:type_name -> aether.platform.v1.common.PageResponse
	0,  // 8: aether.platform.v1.registry.GetModuleResponse.module:type_name -> aether.platform.v1.registry.Module
	0,  // 9: aether.platform.v1.registry.DeprecateModuleResponse.module:type_name -> aether.platform.v1.registry.Module
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_platform_v1_registry_dto_proto_init() }
func file_platform_v1_registry_dto_proto_init() {
	if File_platform_v1_registry_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_registry_dto_proto_rawDesc), len(file_platform_v1_registry_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_registry_dto_proto_goTypes,
		DependencyIndexes: file_platform_v1_registry_dto_proto_depIdxs,
		MessageInfos:      file_platform_v1_registry_dto_proto_msgTypes,
	}.Build()
	File_platform_v1_registry_dto_proto = out.File
	file_platform_v1_registry_dto_proto_goTypes = nil
	file_platform_v1_registry_dto_proto_depIdxs = nil
}
