// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/common.proto

package platformv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor_ActorType int32

const (
	Actor_ACTOR_TYPE_UNSPECIFIED Actor_ActorType = 0
	Actor_ACTOR_TYPE_HUMAN       Actor_ActorType = 1
	Actor_ACTOR_TYPE_AI          Actor_ActorType = 2
	Actor_ACTOR_TYPE_SYSTEM      Actor_ActorType = 3
)

// Enum value maps for Actor_ActorType.
var (
	Actor_ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_HUMAN",
		2: "ACTOR_TYPE_AI",
		3: "ACTOR_TYPE_SYSTEM",
	}
	Actor_ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_HUMAN":       1,
		"ACTOR_TYPE_AI":          2,
		"ACTOR_TYPE_SYSTEM":      3,
	}
)

func (x Actor_ActorType) Enum() *Actor_ActorType {
	p := new(Actor_ActorType)
	*p = x
	return p
}

func (x Actor_ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actor_ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_proto_enumTypes[0].Descriptor()
}

func (Actor_ActorType) Type() protoreflect.EnumType {
	return &file_platform_v1_common_proto_enumTypes[0]
}

func (x Actor_ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actor_ActorType.Descriptor instead.
func (Actor_ActorType) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{2, 0}
}

// PageRequest is embedded in list RPC requests for pagination.
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_platform_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// PageResponse is embedded in list RPC responses for pagination.
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_platform_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Actor is the unified identity model (D10/D10.1).
type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Actor_ActorType        `protobuf:"varint,1,opt,name=type,proto3,enum=aether.platform.v1.Actor_ActorType" json:"type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_platform_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Actor) GetType() Actor_ActorType {
	if x != nil {
		return x.Type
	}
	return Actor_ACTOR_TYPE_UNSPECIFIED
}

func (x *Actor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Actor) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// ModuleVersion describes a registered Terraform module version.
type ModuleVersion struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Version               string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                            // semver e.g. v1.2.0
	CommitSha             string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`                                       // sha256:<hex>
	Providers             []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`                                                        // e.g. ["aws@>=5.0"]
	VariablesContractJson string                 `protobuf:"bytes,4,opt,name=variables_contract_json,json=variablesContractJson,proto3" json:"variables_contract_json,omitempty"` // parsed from variables.tf
	Dependencies          []*ModuleDependency    `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                                                  // declared cross-module deps
	RegisteredAt          string                 `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ModuleVersion) Reset() {
	*x = ModuleVersion{}
	mi := &file_platform_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleVersion) ProtoMessage() {}

func (x *ModuleVersion) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleVersion.ProtoReflect.Descriptor instead.
func (*ModuleVersion) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleVersion) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ModuleVersion) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ModuleVersion) GetVariablesContractJson() string {
	if x != nil {
		return x.VariablesContractJson
	}
	return ""
}

func (x *ModuleVersion) GetDependencies() []*ModuleDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ModuleVersion) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

// ModuleDependency declares a cross-module dependency (from variables.tf).
// Example: ECS module depends on VPC module's vswitch_id output.
type ModuleDependency struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VariableName    string                 `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`            // e.g. "vswitch_id"
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                  // e.g. "VSwitch ID for the ECS instance"
	DependsOnLayer  string                 `protobuf:"bytes,3,opt,name=depends_on_layer,json=dependsOnLayer,proto3" json:"depends_on_layer,omitempty"`    // e.g. "global"
	DependsOnModule string                 `protobuf:"bytes,4,opt,name=depends_on_module,json=dependsOnModule,proto3" json:"depends_on_module,omitempty"` // e.g. "vpc"
	OutputKey       string                 `protobuf:"bytes,5,opt,name=output_key,json=outputKey,proto3" json:"output_key,omitempty"`                     // e.g. "vswitch_id"
	Required        bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`                                       // whether this dependency is mandatory
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModuleDependency) Reset() {
	*x = ModuleDependency{}
	mi := &file_platform_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDependency) ProtoMessage() {}

func (x *ModuleDependency) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDependency.ProtoReflect.Descriptor instead.
func (*ModuleDependency) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ModuleDependency) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *ModuleDependency) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleDependency) GetDependsOnLayer() string {
	if x != nil {
		return x.DependsOnLayer
	}
	return ""
}

func (x *ModuleDependency) GetDependsOnModule() string {
	if x != nil {
		return x.DependsOnModule
	}
	return ""
}

func (x *ModuleDependency) GetOutputKey() string {
	if x != nil {
		return x.OutputKey
	}
	return ""
}

func (x *ModuleDependency) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_platform_v1_common_proto protoreflect.FileDescriptor

const file_platform_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18platform/v1/common.proto\x12\x12aether.platform.v1\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"6\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\"\xdb\x01\n" +
	"\x05Actor\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.aether.platform.v1.Actor.ActorTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\"g\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_TYPE_HUMAN\x10\x01\x12\x11\n" +
	"\rACTOR_TYPE_AI\x10\x02\x12\x15\n" +
	"\x11ACTOR_TYPE_SYSTEM\x10\x03\"\x8d\x02\n" +
	"\rModuleVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x126\n" +
	"\x17variables_contract_json\x18\x04 \x01(\tR\x15variablesContractJson\x12H\n" +
	"\fdependencies\x18\x05 \x03(\v2$.aether.platform.v1.ModuleDependencyR\fdependencies\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\tR\fregisteredAt\"\xea\x01\n" +
	"\x10ModuleDependency\x12#\n" +
	"\rvariable_name\x18\x01 \x01(\tR\fvariableName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10depends_on_layer\x18\x03 \x01(\tR\x0edependsOnLayer\x12*\n" +
	"\x11depends_on_module\x18\x04 \x01(\tR\x0fdependsOnModule\x12\x1d\n" +
	"\n" +
	"output_key\x18\x05 \x01(\tR\toutputKey\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequiredBUZSgithub.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_common_proto_rawDescOnce sync.Once
	file_platform_v1_common_proto_rawDescData []byte
)

func file_platform_v1_common_proto_rawDescGZIP() []byte {
	file_platform_v1_common_proto_rawDescOnce.Do(func() {
		file_platform_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_common_proto_rawDesc), len(file_platform_v1_common_proto_rawDesc)))
	})
	return file_platform_v1_common_proto_rawDescData
}

var file_platform_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_platform_v1_common_proto_goTypes = []any{
	(Actor_ActorType)(0),     // 0: aether.platform.v1.Actor.ActorType
	(*PageRequest)(nil),      // 1: aether.platform.v1.PageRequest
	(*PageResponse)(nil),     // 2: aether.platform.v1.PageResponse
	(*Actor)(nil),            // 3: aether.platform.v1.Actor
	(*ModuleVersion)(nil),    // 4: aether.platform.v1.ModuleVersion
	(*ModuleDependency)(nil), // 5: aether.platform.v1.ModuleDependency
}
var file_platform_v1_common_proto_depIdxs = []int32{
	0, // 0: aether.platform.v1.Actor.type:type_name -> aether.platform.v1.Actor.ActorType
	5, // 1: aether.platform.v1.ModuleVersion.dependencies:type_name -> aether.platform.v1.ModuleDependency
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_platform_v1_common_proto_init() }
func file_platform_v1_common_proto_init() {
	if File_platform_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_common_proto_rawDesc), len(file_platform_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_common_proto_goTypes,
		DependencyIndexes: file_platform_v1_common_proto_depIdxs,
		EnumInfos:         file_platform_v1_common_proto_enumTypes,
		MessageInfos:      file_platform_v1_common_proto_msgTypes,
	}.Build()
	File_platform_v1_common_proto = out.File
	file_platform_v1_common_proto_goTypes = nil
	file_platform_v1_common_proto_depIdxs = nil
}
