// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/planning.proto

package platformv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanArtifact_ArtifactStatus int32

const (
	PlanArtifact_ARTIFACT_STATUS_UNSPECIFIED PlanArtifact_ArtifactStatus = 0
	PlanArtifact_ARTIFACT_STATUS_READY       PlanArtifact_ArtifactStatus = 1
	PlanArtifact_ARTIFACT_STATUS_EXPIRED     PlanArtifact_ArtifactStatus = 2
	PlanArtifact_ARTIFACT_STATUS_CONSUMED    PlanArtifact_ArtifactStatus = 3
)

// Enum value maps for PlanArtifact_ArtifactStatus.
var (
	PlanArtifact_ArtifactStatus_name = map[int32]string{
		0: "ARTIFACT_STATUS_UNSPECIFIED",
		1: "ARTIFACT_STATUS_READY",
		2: "ARTIFACT_STATUS_EXPIRED",
		3: "ARTIFACT_STATUS_CONSUMED",
	}
	PlanArtifact_ArtifactStatus_value = map[string]int32{
		"ARTIFACT_STATUS_UNSPECIFIED": 0,
		"ARTIFACT_STATUS_READY":       1,
		"ARTIFACT_STATUS_EXPIRED":     2,
		"ARTIFACT_STATUS_CONSUMED":    3,
	}
)

func (x PlanArtifact_ArtifactStatus) Enum() *PlanArtifact_ArtifactStatus {
	p := new(PlanArtifact_ArtifactStatus)
	*p = x
	return p
}

func (x PlanArtifact_ArtifactStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanArtifact_ArtifactStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_planning_proto_enumTypes[0].Descriptor()
}

func (PlanArtifact_ArtifactStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_planning_proto_enumTypes[0]
}

func (x PlanArtifact_ArtifactStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanArtifact_ArtifactStatus.Descriptor instead.
func (PlanArtifact_ArtifactStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{0, 0}
}

type PlanArtifact struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Id                string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // art_<alphanum>
	RequestId         string                      `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status            PlanArtifact_ArtifactStatus `protobuf:"varint,3,opt,name=status,proto3,enum=aether.platform.v1.PlanArtifact_ArtifactStatus" json:"status,omitempty"`
	PlanHash          string                      `protobuf:"bytes,4,opt,name=plan_hash,json=planHash,proto3" json:"plan_hash,omitempty"` // sha256:<hex>
	Summary           *PlanSummary                `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CostEstimateCents int64                       `protobuf:"varint,6,opt,name=cost_estimate_cents,json=costEstimateCents,proto3" json:"cost_estimate_cents,omitempty"`
	StorageUri        string                      `protobuf:"bytes,7,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ExpiresAt         string                      `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC 3339 UTC
	CreatedAt         string                      `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanArtifact) Reset() {
	*x = PlanArtifact{}
	mi := &file_platform_v1_planning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanArtifact) ProtoMessage() {}

func (x *PlanArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanArtifact.ProtoReflect.Descriptor instead.
func (*PlanArtifact) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{0}
}

func (x *PlanArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanArtifact) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PlanArtifact) GetStatus() PlanArtifact_ArtifactStatus {
	if x != nil {
		return x.Status
	}
	return PlanArtifact_ARTIFACT_STATUS_UNSPECIFIED
}

func (x *PlanArtifact) GetPlanHash() string {
	if x != nil {
		return x.PlanHash
	}
	return ""
}

func (x *PlanArtifact) GetSummary() *PlanSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *PlanArtifact) GetCostEstimateCents() int64 {
	if x != nil {
		return x.CostEstimateCents
	}
	return 0
}

func (x *PlanArtifact) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *PlanArtifact) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PlanArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PlanSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourcesToAdd     int32                  `protobuf:"varint,1,opt,name=resources_to_add,json=resourcesToAdd,proto3" json:"resources_to_add,omitempty"`
	ResourcesToChange  int32                  `protobuf:"varint,2,opt,name=resources_to_change,json=resourcesToChange,proto3" json:"resources_to_change,omitempty"`
	ResourcesToDestroy int32                  `protobuf:"varint,3,opt,name=resources_to_destroy,json=resourcesToDestroy,proto3" json:"resources_to_destroy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlanSummary) Reset() {
	*x = PlanSummary{}
	mi := &file_platform_v1_planning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanSummary) ProtoMessage() {}

func (x *PlanSummary) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanSummary.ProtoReflect.Descriptor instead.
func (*PlanSummary) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{1}
}

func (x *PlanSummary) GetResourcesToAdd() int32 {
	if x != nil {
		return x.ResourcesToAdd
	}
	return 0
}

func (x *PlanSummary) GetResourcesToChange() int32 {
	if x != nil {
		return x.ResourcesToChange
	}
	return 0
}

func (x *PlanSummary) GetResourcesToDestroy() int32 {
	if x != nil {
		return x.ResourcesToDestroy
	}
	return 0
}

type StartPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPlanRequest) Reset() {
	*x = StartPlanRequest{}
	mi := &file_platform_v1_planning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanRequest) ProtoMessage() {}

func (x *StartPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanRequest.ProtoReflect.Descriptor instead.
func (*StartPlanRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{2}
}

func (x *StartPlanRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StartPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"` // updated request with status=planning
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPlanResponse) Reset() {
	*x = StartPlanResponse{}
	mi := &file_platform_v1_planning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPlanResponse) ProtoMessage() {}

func (x *StartPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPlanResponse.ProtoReflect.Descriptor instead.
func (*StartPlanResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{3}
}

func (x *StartPlanResponse) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *StartPlanResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_platform_v1_planning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type GetArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *PlanArtifact          `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactResponse) Reset() {
	*x = GetArtifactResponse{}
	mi := &file_platform_v1_planning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactResponse) ProtoMessage() {}

func (x *GetArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_planning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactResponse.ProtoReflect.Descriptor instead.
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_planning_proto_rawDescGZIP(), []int{5}
}

func (x *GetArtifactResponse) GetArtifact() *PlanArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *GetArtifactResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_platform_v1_planning_proto protoreflect.FileDescriptor

const file_platform_v1_planning_proto_rawDesc = "" +
	"\n" +
	"\x1aplatform/v1/planning.proto\x12\x12aether.platform.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19platform/v1/request.proto\"\xf7\x03\n" +
	"\fPlanArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12G\n" +
	"\x06status\x18\x03 \x01(\x0e2/.aether.platform.v1.PlanArtifact.ArtifactStatusR\x06status\x12\x1b\n" +
	"\tplan_hash\x18\x04 \x01(\tR\bplanHash\x129\n" +
	"\asummary\x18\x05 \x01(\v2\x1f.aether.platform.v1.PlanSummaryR\asummary\x12.\n" +
	"\x13cost_estimate_cents\x18\x06 \x01(\x03R\x11costEstimateCents\x12\x1f\n" +
	"\vstorage_uri\x18\a \x01(\tR\n" +
	"storageUri\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x87\x01\n" +
	"\x0eArtifactStatus\x12\x1f\n" +
	"\x1bARTIFACT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ARTIFACT_STATUS_READY\x10\x01\x12\x1b\n" +
	"\x17ARTIFACT_STATUS_EXPIRED\x10\x02\x12\x1c\n" +
	"\x18ARTIFACT_STATUS_CONSUMED\x10\x03\"\x99\x01\n" +
	"\vPlanSummary\x12(\n" +
	"\x10resources_to_add\x18\x01 \x01(\x05R\x0eresourcesToAdd\x12.\n" +
	"\x13resources_to_change\x18\x02 \x01(\x05R\x11resourcesToChange\x120\n" +
	"\x14resources_to_destroy\x18\x03 \x01(\x05R\x12resourcesToDestroy\"1\n" +
	"\x10StartPlanRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"q\n" +
	"\x11StartPlanResponse\x125\n" +
	"\arequest\x18\x01 \x01(\v2\x1b.aether.platform.v1.RequestR\arequest\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"z\n" +
	"\x13GetArtifactResponse\x12<\n" +
	"\bartifact\x18\x01 \x01(\v2 .aether.platform.v1.PlanArtifactR\bartifact\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId2\x94\x01\n" +
	"\x0fPlanningService\x12\x80\x01\n" +
	"\tStartPlan\x12$.aether.platform.v1.StartPlanRequest\x1a%.aether.platform.v1.StartPlanResponse\"&\x82\xd3\xe4\x93\x02 \"\x1e/v1/requests/{request_id}/plan2\x97\x01\n" +
	"\x0fArtifactService\x12\x83\x01\n" +
	"\vGetArtifact\x12&.aether.platform.v1.GetArtifactRequest\x1a'.aether.platform.v1.GetArtifactResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/artifacts/{artifact_id}BUZSgithub.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1;platformv1b\x06proto3"

var (
	file_platform_v1_planning_proto_rawDescOnce sync.Once
	file_platform_v1_planning_proto_rawDescData []byte
)

func file_platform_v1_planning_proto_rawDescGZIP() []byte {
	file_platform_v1_planning_proto_rawDescOnce.Do(func() {
		file_platform_v1_planning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_planning_proto_rawDesc), len(file_platform_v1_planning_proto_rawDesc)))
	})
	return file_platform_v1_planning_proto_rawDescData
}

var file_platform_v1_planning_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_v1_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_platform_v1_planning_proto_goTypes = []any{
	(PlanArtifact_ArtifactStatus)(0), // 0: aether.platform.v1.PlanArtifact.ArtifactStatus
	(*PlanArtifact)(nil),             // 1: aether.platform.v1.PlanArtifact
	(*PlanSummary)(nil),              // 2: aether.platform.v1.PlanSummary
	(*StartPlanRequest)(nil),         // 3: aether.platform.v1.StartPlanRequest
	(*StartPlanResponse)(nil),        // 4: aether.platform.v1.StartPlanResponse
	(*GetArtifactRequest)(nil),       // 5: aether.platform.v1.GetArtifactRequest
	(*GetArtifactResponse)(nil),      // 6: aether.platform.v1.GetArtifactResponse
	(*Request)(nil),                  // 7: aether.platform.v1.Request
}
var file_platform_v1_planning_proto_depIdxs = []int32{
	0, // 0: aether.platform.v1.PlanArtifact.status:type_name -> aether.platform.v1.PlanArtifact.ArtifactStatus
	2, // 1: aether.platform.v1.PlanArtifact.summary:type_name -> aether.platform.v1.PlanSummary
	7, // 2: aether.platform.v1.StartPlanResponse.request:type_name -> aether.platform.v1.Request
	1, // 3: aether.platform.v1.GetArtifactResponse.artifact:type_name -> aether.platform.v1.PlanArtifact
	3, // 4: aether.platform.v1.PlanningService.StartPlan:input_type -> aether.platform.v1.StartPlanRequest
	5, // 5: aether.platform.v1.ArtifactService.GetArtifact:input_type -> aether.platform.v1.GetArtifactRequest
	4, // 6: aether.platform.v1.PlanningService.StartPlan:output_type -> aether.platform.v1.StartPlanResponse
	6, // 7: aether.platform.v1.ArtifactService.GetArtifact:output_type -> aether.platform.v1.GetArtifactResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_platform_v1_planning_proto_init() }
func file_platform_v1_planning_proto_init() {
	if File_platform_v1_planning_proto != nil {
		return
	}
	file_platform_v1_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_planning_proto_rawDesc), len(file_platform_v1_planning_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_platform_v1_planning_proto_goTypes,
		DependencyIndexes: file_platform_v1_planning_proto_depIdxs,
		EnumInfos:         file_platform_v1_planning_proto_enumTypes,
		MessageInfos:      file_platform_v1_planning_proto_msgTypes,
	}.Build()
	File_platform_v1_planning_proto = out.File
	file_platform_v1_planning_proto_goTypes = nil
	file_platform_v1_planning_proto_depIdxs = nil
}
