// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/common/dto.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageRequest is embedded in list RPC requests.
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_platform_v1_common_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_dto_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// PageResponse is embedded in list RPC responses.
type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_platform_v1_common_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_dto_proto_rawDescGZIP(), []int{1}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Actor is the unified identity model (D10/D10.1).
type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActorType              `protobuf:"varint,1,opt,name=type,proto3,enum=aether.platform.v1.common.ActorType" json:"type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_platform_v1_common_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_platform_v1_common_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_platform_v1_common_dto_proto_rawDescGZIP(), []int{2}
}

func (x *Actor) GetType() ActorType {
	if x != nil {
		return x.Type
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *Actor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Actor) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

var File_platform_v1_common_dto_proto protoreflect.FileDescriptor

const file_platform_v1_common_dto_proto_rawDesc = "" +
	"\n" +
	"\x1cplatform/v1/common/dto.proto\x12\x19aether.platform.v1.common\x1a\x1dplatform/v1/common/enum.proto\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"6\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\"s\n" +
	"\x05Actor\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.aether.platform.v1.common.ActorTypeR\x04type\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamIdBZZXgithub.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/common;commonv1b\x06proto3"

var (
	file_platform_v1_common_dto_proto_rawDescOnce sync.Once
	file_platform_v1_common_dto_proto_rawDescData []byte
)

func file_platform_v1_common_dto_proto_rawDescGZIP() []byte {
	file_platform_v1_common_dto_proto_rawDescOnce.Do(func() {
		file_platform_v1_common_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_common_dto_proto_rawDesc), len(file_platform_v1_common_dto_proto_rawDesc)))
	})
	return file_platform_v1_common_dto_proto_rawDescData
}

var file_platform_v1_common_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_v1_common_dto_proto_goTypes = []any{
	(*PageRequest)(nil),  // 0: aether.platform.v1.common.PageRequest
	(*PageResponse)(nil), // 1: aether.platform.v1.common.PageResponse
	(*Actor)(nil),        // 2: aether.platform.v1.common.Actor
	(ActorType)(0),       // 3: aether.platform.v1.common.ActorType
}
var file_platform_v1_common_dto_proto_depIdxs = []int32{
	3, // 0: aether.platform.v1.common.Actor.type:type_name -> aether.platform.v1.common.ActorType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platform_v1_common_dto_proto_init() }
func file_platform_v1_common_dto_proto_init() {
	if File_platform_v1_common_dto_proto != nil {
		return
	}
	file_platform_v1_common_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_common_dto_proto_rawDesc), len(file_platform_v1_common_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_common_dto_proto_goTypes,
		DependencyIndexes: file_platform_v1_common_dto_proto_depIdxs,
		MessageInfos:      file_platform_v1_common_dto_proto_msgTypes,
	}.Build()
	File_platform_v1_common_dto_proto = out.File
	file_platform_v1_common_dto_proto_goTypes = nil
	file_platform_v1_common_dto_proto_depIdxs = nil
}
