// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/common/enum.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	ActorType_ACTOR_TYPE_HUMAN       ActorType = 1
	ActorType_ACTOR_TYPE_AI          ActorType = 2
	ActorType_ACTOR_TYPE_SYSTEM      ActorType = 3
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_HUMAN",
		2: "ACTOR_TYPE_AI",
		3: "ACTOR_TYPE_SYSTEM",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_HUMAN":       1,
		"ACTOR_TYPE_AI":          2,
		"ACTOR_TYPE_SYSTEM":      3,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{0}
}

type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED       RequestStatus = 0
	RequestStatus_REQUEST_STATUS_SUBMITTED         RequestStatus = 1
	RequestStatus_REQUEST_STATUS_GENERATING        RequestStatus = 2
	RequestStatus_REQUEST_STATUS_PENDING_ADMISSION RequestStatus = 3
	RequestStatus_REQUEST_STATUS_PLANNING          RequestStatus = 4
	RequestStatus_REQUEST_STATUS_PLAN_READY        RequestStatus = 5
	RequestStatus_REQUEST_STATUS_PENDING_APPROVAL  RequestStatus = 6
	RequestStatus_REQUEST_STATUS_APPLYING          RequestStatus = 7
	RequestStatus_REQUEST_STATUS_RECONCILING       RequestStatus = 8
	RequestStatus_REQUEST_STATUS_SUCCEEDED         RequestStatus = 9
	RequestStatus_REQUEST_STATUS_REJECTED          RequestStatus = 10
	RequestStatus_REQUEST_STATUS_CANCELLED         RequestStatus = 11
	RequestStatus_REQUEST_STATUS_EXPIRED           RequestStatus = 12
	RequestStatus_REQUEST_STATUS_FAILED_RETRYABLE  RequestStatus = 13
	RequestStatus_REQUEST_STATUS_FAILED_TERMINAL   RequestStatus = 14
	RequestStatus_REQUEST_STATUS_WAITING_MANUAL    RequestStatus = 15
	RequestStatus_REQUEST_STATUS_RECONCILE_PENDING RequestStatus = 16
	// Health/policy blocked states (doc 12a RLC-111/112/115, Phase 1 acceptance).
	// External-system-caused blocks that auto-resume on recovery (unlike
	// waiting_manual which needs human action).
	RequestStatus_REQUEST_STATUS_BLOCKED_POLICY       RequestStatus = 17
	RequestStatus_REQUEST_STATUS_BLOCKED_STATE_HEALTH RequestStatus = 18
	RequestStatus_REQUEST_STATUS_PAUSED_DRIFT         RequestStatus = 19
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0:  "REQUEST_STATUS_UNSPECIFIED",
		1:  "REQUEST_STATUS_SUBMITTED",
		2:  "REQUEST_STATUS_GENERATING",
		3:  "REQUEST_STATUS_PENDING_ADMISSION",
		4:  "REQUEST_STATUS_PLANNING",
		5:  "REQUEST_STATUS_PLAN_READY",
		6:  "REQUEST_STATUS_PENDING_APPROVAL",
		7:  "REQUEST_STATUS_APPLYING",
		8:  "REQUEST_STATUS_RECONCILING",
		9:  "REQUEST_STATUS_SUCCEEDED",
		10: "REQUEST_STATUS_REJECTED",
		11: "REQUEST_STATUS_CANCELLED",
		12: "REQUEST_STATUS_EXPIRED",
		13: "REQUEST_STATUS_FAILED_RETRYABLE",
		14: "REQUEST_STATUS_FAILED_TERMINAL",
		15: "REQUEST_STATUS_WAITING_MANUAL",
		16: "REQUEST_STATUS_RECONCILE_PENDING",
		17: "REQUEST_STATUS_BLOCKED_POLICY",
		18: "REQUEST_STATUS_BLOCKED_STATE_HEALTH",
		19: "REQUEST_STATUS_PAUSED_DRIFT",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_UNSPECIFIED":          0,
		"REQUEST_STATUS_SUBMITTED":            1,
		"REQUEST_STATUS_GENERATING":           2,
		"REQUEST_STATUS_PENDING_ADMISSION":    3,
		"REQUEST_STATUS_PLANNING":             4,
		"REQUEST_STATUS_PLAN_READY":           5,
		"REQUEST_STATUS_PENDING_APPROVAL":     6,
		"REQUEST_STATUS_APPLYING":             7,
		"REQUEST_STATUS_RECONCILING":          8,
		"REQUEST_STATUS_SUCCEEDED":            9,
		"REQUEST_STATUS_REJECTED":             10,
		"REQUEST_STATUS_CANCELLED":            11,
		"REQUEST_STATUS_EXPIRED":              12,
		"REQUEST_STATUS_FAILED_RETRYABLE":     13,
		"REQUEST_STATUS_FAILED_TERMINAL":      14,
		"REQUEST_STATUS_WAITING_MANUAL":       15,
		"REQUEST_STATUS_RECONCILE_PENDING":    16,
		"REQUEST_STATUS_BLOCKED_POLICY":       17,
		"REQUEST_STATUS_BLOCKED_STATE_HEALTH": 18,
		"REQUEST_STATUS_PAUSED_DRIFT":         19,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[1].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[1]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{1}
}

type RequestSource int32

const (
	RequestSource_REQUEST_SOURCE_UNSPECIFIED RequestSource = 0
	RequestSource_REQUEST_SOURCE_WEB         RequestSource = 1
	RequestSource_REQUEST_SOURCE_CLI         RequestSource = 2
	RequestSource_REQUEST_SOURCE_CICD        RequestSource = 3
	RequestSource_REQUEST_SOURCE_AI          RequestSource = 4
	RequestSource_REQUEST_SOURCE_GATEWAY     RequestSource = 5
)

// Enum value maps for RequestSource.
var (
	RequestSource_name = map[int32]string{
		0: "REQUEST_SOURCE_UNSPECIFIED",
		1: "REQUEST_SOURCE_WEB",
		2: "REQUEST_SOURCE_CLI",
		3: "REQUEST_SOURCE_CICD",
		4: "REQUEST_SOURCE_AI",
		5: "REQUEST_SOURCE_GATEWAY",
	}
	RequestSource_value = map[string]int32{
		"REQUEST_SOURCE_UNSPECIFIED": 0,
		"REQUEST_SOURCE_WEB":         1,
		"REQUEST_SOURCE_CLI":         2,
		"REQUEST_SOURCE_CICD":        3,
		"REQUEST_SOURCE_AI":          4,
		"REQUEST_SOURCE_GATEWAY":     5,
	}
)

func (x RequestSource) Enum() *RequestSource {
	p := new(RequestSource)
	*p = x
	return p
}

func (x RequestSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestSource) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[2].Descriptor()
}

func (RequestSource) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[2]
}

func (x RequestSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestSource.Descriptor instead.
func (RequestSource) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{2}
}

type ApprovalDecision int32

const (
	ApprovalDecision_APPROVAL_DECISION_UNSPECIFIED ApprovalDecision = 0
	ApprovalDecision_APPROVAL_DECISION_APPROVED    ApprovalDecision = 1
	ApprovalDecision_APPROVAL_DECISION_REJECTED    ApprovalDecision = 2
)

// Enum value maps for ApprovalDecision.
var (
	ApprovalDecision_name = map[int32]string{
		0: "APPROVAL_DECISION_UNSPECIFIED",
		1: "APPROVAL_DECISION_APPROVED",
		2: "APPROVAL_DECISION_REJECTED",
	}
	ApprovalDecision_value = map[string]int32{
		"APPROVAL_DECISION_UNSPECIFIED": 0,
		"APPROVAL_DECISION_APPROVED":    1,
		"APPROVAL_DECISION_REJECTED":    2,
	}
)

func (x ApprovalDecision) Enum() *ApprovalDecision {
	p := new(ApprovalDecision)
	*p = x
	return p
}

func (x ApprovalDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[3].Descriptor()
}

func (ApprovalDecision) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[3]
}

func (x ApprovalDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalDecision.Descriptor instead.
func (ApprovalDecision) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{3}
}

type ApprovalRunStatus int32

const (
	ApprovalRunStatus_APPROVAL_RUN_STATUS_UNSPECIFIED ApprovalRunStatus = 0
	ApprovalRunStatus_APPROVAL_RUN_STATUS_PENDING     ApprovalRunStatus = 1
	ApprovalRunStatus_APPROVAL_RUN_STATUS_APPROVED    ApprovalRunStatus = 2
	ApprovalRunStatus_APPROVAL_RUN_STATUS_REJECTED    ApprovalRunStatus = 3
	ApprovalRunStatus_APPROVAL_RUN_STATUS_EXPIRED     ApprovalRunStatus = 4
)

// Enum value maps for ApprovalRunStatus.
var (
	ApprovalRunStatus_name = map[int32]string{
		0: "APPROVAL_RUN_STATUS_UNSPECIFIED",
		1: "APPROVAL_RUN_STATUS_PENDING",
		2: "APPROVAL_RUN_STATUS_APPROVED",
		3: "APPROVAL_RUN_STATUS_REJECTED",
		4: "APPROVAL_RUN_STATUS_EXPIRED",
	}
	ApprovalRunStatus_value = map[string]int32{
		"APPROVAL_RUN_STATUS_UNSPECIFIED": 0,
		"APPROVAL_RUN_STATUS_PENDING":     1,
		"APPROVAL_RUN_STATUS_APPROVED":    2,
		"APPROVAL_RUN_STATUS_REJECTED":    3,
		"APPROVAL_RUN_STATUS_EXPIRED":     4,
	}
)

func (x ApprovalRunStatus) Enum() *ApprovalRunStatus {
	p := new(ApprovalRunStatus)
	*p = x
	return p
}

func (x ApprovalRunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalRunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[4].Descriptor()
}

func (ApprovalRunStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[4]
}

func (x ApprovalRunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalRunStatus.Descriptor instead.
func (ApprovalRunStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{4}
}

type ArtifactStatus int32

const (
	ArtifactStatus_ARTIFACT_STATUS_UNSPECIFIED ArtifactStatus = 0
	ArtifactStatus_ARTIFACT_STATUS_READY       ArtifactStatus = 1
	ArtifactStatus_ARTIFACT_STATUS_EXPIRED     ArtifactStatus = 2
	ArtifactStatus_ARTIFACT_STATUS_CONSUMED    ArtifactStatus = 3
	// Plan was superseded by a newer plan (drift guard re-plan, or approval
	// reject followed by re-plan). Kept for audit, not applyable (doc 12 §3.5).
	ArtifactStatus_ARTIFACT_STATUS_SUPERSEDED ArtifactStatus = 4
)

// Enum value maps for ArtifactStatus.
var (
	ArtifactStatus_name = map[int32]string{
		0: "ARTIFACT_STATUS_UNSPECIFIED",
		1: "ARTIFACT_STATUS_READY",
		2: "ARTIFACT_STATUS_EXPIRED",
		3: "ARTIFACT_STATUS_CONSUMED",
		4: "ARTIFACT_STATUS_SUPERSEDED",
	}
	ArtifactStatus_value = map[string]int32{
		"ARTIFACT_STATUS_UNSPECIFIED": 0,
		"ARTIFACT_STATUS_READY":       1,
		"ARTIFACT_STATUS_EXPIRED":     2,
		"ARTIFACT_STATUS_CONSUMED":    3,
		"ARTIFACT_STATUS_SUPERSEDED":  4,
	}
)

func (x ArtifactStatus) Enum() *ArtifactStatus {
	p := new(ArtifactStatus)
	*p = x
	return p
}

func (x ArtifactStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[5].Descriptor()
}

func (ArtifactStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[5]
}

func (x ArtifactStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactStatus.Descriptor instead.
func (ArtifactStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{5}
}

type GateSeverity int32

const (
	GateSeverity_GATE_SEVERITY_UNSPECIFIED GateSeverity = 0
	GateSeverity_GATE_SEVERITY_ERROR       GateSeverity = 1
	GateSeverity_GATE_SEVERITY_WARNING     GateSeverity = 2
)

// Enum value maps for GateSeverity.
var (
	GateSeverity_name = map[int32]string{
		0: "GATE_SEVERITY_UNSPECIFIED",
		1: "GATE_SEVERITY_ERROR",
		2: "GATE_SEVERITY_WARNING",
	}
	GateSeverity_value = map[string]int32{
		"GATE_SEVERITY_UNSPECIFIED": 0,
		"GATE_SEVERITY_ERROR":       1,
		"GATE_SEVERITY_WARNING":     2,
	}
)

func (x GateSeverity) Enum() *GateSeverity {
	p := new(GateSeverity)
	*p = x
	return p
}

func (x GateSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[6].Descriptor()
}

func (GateSeverity) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[6]
}

func (x GateSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateSeverity.Descriptor instead.
func (GateSeverity) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{6}
}

type ModuleStatus int32

const (
	ModuleStatus_MODULE_STATUS_UNSPECIFIED        ModuleStatus = 0
	ModuleStatus_MODULE_STATUS_PENDING_VALIDATION ModuleStatus = 1
	ModuleStatus_MODULE_STATUS_VALIDATED          ModuleStatus = 2
	ModuleStatus_MODULE_STATUS_VALIDATION_FAILED  ModuleStatus = 3
	ModuleStatus_MODULE_STATUS_DEPRECATED         ModuleStatus = 4
)

// Enum value maps for ModuleStatus.
var (
	ModuleStatus_name = map[int32]string{
		0: "MODULE_STATUS_UNSPECIFIED",
		1: "MODULE_STATUS_PENDING_VALIDATION",
		2: "MODULE_STATUS_VALIDATED",
		3: "MODULE_STATUS_VALIDATION_FAILED",
		4: "MODULE_STATUS_DEPRECATED",
	}
	ModuleStatus_value = map[string]int32{
		"MODULE_STATUS_UNSPECIFIED":        0,
		"MODULE_STATUS_PENDING_VALIDATION": 1,
		"MODULE_STATUS_VALIDATED":          2,
		"MODULE_STATUS_VALIDATION_FAILED":  3,
		"MODULE_STATUS_DEPRECATED":         4,
	}
)

func (x ModuleStatus) Enum() *ModuleStatus {
	p := new(ModuleStatus)
	*p = x
	return p
}

func (x ModuleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[7].Descriptor()
}

func (ModuleStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[7]
}

func (x ModuleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleStatus.Descriptor instead.
func (ModuleStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{7}
}

type CatalogItemStatus int32

const (
	CatalogItemStatus_CATALOG_ITEM_STATUS_UNSPECIFIED CatalogItemStatus = 0
	// Lifecycle: draft → active → deprecated → archived (doc 19 §1).
	// blocked = security/compliance/toolchain issue (doc 19 §1).
	CatalogItemStatus_CATALOG_ITEM_STATUS_DRAFT      CatalogItemStatus = 1
	CatalogItemStatus_CATALOG_ITEM_STATUS_ACTIVE     CatalogItemStatus = 2
	CatalogItemStatus_CATALOG_ITEM_STATUS_DEPRECATED CatalogItemStatus = 3
	CatalogItemStatus_CATALOG_ITEM_STATUS_ARCHIVED   CatalogItemStatus = 4
	CatalogItemStatus_CATALOG_ITEM_STATUS_BLOCKED    CatalogItemStatus = 5
)

// Enum value maps for CatalogItemStatus.
var (
	CatalogItemStatus_name = map[int32]string{
		0: "CATALOG_ITEM_STATUS_UNSPECIFIED",
		1: "CATALOG_ITEM_STATUS_DRAFT",
		2: "CATALOG_ITEM_STATUS_ACTIVE",
		3: "CATALOG_ITEM_STATUS_DEPRECATED",
		4: "CATALOG_ITEM_STATUS_ARCHIVED",
		5: "CATALOG_ITEM_STATUS_BLOCKED",
	}
	CatalogItemStatus_value = map[string]int32{
		"CATALOG_ITEM_STATUS_UNSPECIFIED": 0,
		"CATALOG_ITEM_STATUS_DRAFT":       1,
		"CATALOG_ITEM_STATUS_ACTIVE":      2,
		"CATALOG_ITEM_STATUS_DEPRECATED":  3,
		"CATALOG_ITEM_STATUS_ARCHIVED":    4,
		"CATALOG_ITEM_STATUS_BLOCKED":     5,
	}
)

func (x CatalogItemStatus) Enum() *CatalogItemStatus {
	p := new(CatalogItemStatus)
	*p = x
	return p
}

func (x CatalogItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[8].Descriptor()
}

func (CatalogItemStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[8]
}

func (x CatalogItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatalogItemStatus.Descriptor instead.
func (CatalogItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{8}
}

type Cardinality int32

const (
	Cardinality_CARDINALITY_UNSPECIFIED Cardinality = 0
	Cardinality_CARDINALITY_SINGLE      Cardinality = 1
	Cardinality_CARDINALITY_LIST        Cardinality = 2
	Cardinality_CARDINALITY_MAP         Cardinality = 3
)

// Enum value maps for Cardinality.
var (
	Cardinality_name = map[int32]string{
		0: "CARDINALITY_UNSPECIFIED",
		1: "CARDINALITY_SINGLE",
		2: "CARDINALITY_LIST",
		3: "CARDINALITY_MAP",
	}
	Cardinality_value = map[string]int32{
		"CARDINALITY_UNSPECIFIED": 0,
		"CARDINALITY_SINGLE":      1,
		"CARDINALITY_LIST":        2,
		"CARDINALITY_MAP":         3,
	}
)

func (x Cardinality) Enum() *Cardinality {
	p := new(Cardinality)
	*p = x
	return p
}

func (x Cardinality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cardinality) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[9].Descriptor()
}

func (Cardinality) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[9]
}

func (x Cardinality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cardinality.Descriptor instead.
func (Cardinality) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{9}
}

// StackGranularity is the D24 stack-grouping strategy declared on a
// catalog item. Determines how codegen partitions instances into stacks:
//
//	per-component = one stack per component (default, smallest blast radius)
//	per-space    = one stack per space (coarser, for tightly coupled sets)
//	per-team      = one stack per team (coarsest, rarely used)
//	custom        = path_template override (advanced, admin-only)
type StackGranularity int32

const (
	StackGranularity_STACK_GRANULARITY_UNSPECIFIED   StackGranularity = 0
	StackGranularity_STACK_GRANULARITY_PER_COMPONENT StackGranularity = 1
	StackGranularity_STACK_GRANULARITY_PER_SPACE     StackGranularity = 2
	StackGranularity_STACK_GRANULARITY_PER_TEAM      StackGranularity = 3
	StackGranularity_STACK_GRANULARITY_CUSTOM        StackGranularity = 4
)

// Enum value maps for StackGranularity.
var (
	StackGranularity_name = map[int32]string{
		0: "STACK_GRANULARITY_UNSPECIFIED",
		1: "STACK_GRANULARITY_PER_COMPONENT",
		2: "STACK_GRANULARITY_PER_SPACE",
		3: "STACK_GRANULARITY_PER_TEAM",
		4: "STACK_GRANULARITY_CUSTOM",
	}
	StackGranularity_value = map[string]int32{
		"STACK_GRANULARITY_UNSPECIFIED":   0,
		"STACK_GRANULARITY_PER_COMPONENT": 1,
		"STACK_GRANULARITY_PER_SPACE":     2,
		"STACK_GRANULARITY_PER_TEAM":      3,
		"STACK_GRANULARITY_CUSTOM":        4,
	}
)

func (x StackGranularity) Enum() *StackGranularity {
	p := new(StackGranularity)
	*p = x
	return p
}

func (x StackGranularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StackGranularity) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[10].Descriptor()
}

func (StackGranularity) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[10]
}

func (x StackGranularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StackGranularity.Descriptor instead.
func (StackGranularity) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{10}
}

// StackMigrationStatus is the D26 Tier classification for a stack under a
// layer-rule-set version change. Drives the StateMover / sunset lifecycle.
type StackMigrationStatus int32

const (
	StackMigrationStatus_STACK_MIGRATION_STATUS_UNSPECIFIED       StackMigrationStatus = 0
	StackMigrationStatus_STACK_MIGRATION_STATUS_STABLE            StackMigrationStatus = 1
	StackMigrationStatus_STACK_MIGRATION_STATUS_MIGRATION_PENDING StackMigrationStatus = 2
	StackMigrationStatus_STACK_MIGRATION_STATUS_MIGRATING         StackMigrationStatus = 3
	StackMigrationStatus_STACK_MIGRATION_STATUS_DEPRECATED        StackMigrationStatus = 4
)

// Enum value maps for StackMigrationStatus.
var (
	StackMigrationStatus_name = map[int32]string{
		0: "STACK_MIGRATION_STATUS_UNSPECIFIED",
		1: "STACK_MIGRATION_STATUS_STABLE",
		2: "STACK_MIGRATION_STATUS_MIGRATION_PENDING",
		3: "STACK_MIGRATION_STATUS_MIGRATING",
		4: "STACK_MIGRATION_STATUS_DEPRECATED",
	}
	StackMigrationStatus_value = map[string]int32{
		"STACK_MIGRATION_STATUS_UNSPECIFIED":       0,
		"STACK_MIGRATION_STATUS_STABLE":            1,
		"STACK_MIGRATION_STATUS_MIGRATION_PENDING": 2,
		"STACK_MIGRATION_STATUS_MIGRATING":         3,
		"STACK_MIGRATION_STATUS_DEPRECATED":        4,
	}
)

func (x StackMigrationStatus) Enum() *StackMigrationStatus {
	p := new(StackMigrationStatus)
	*p = x
	return p
}

func (x StackMigrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StackMigrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[11].Descriptor()
}

func (StackMigrationStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[11]
}

func (x StackMigrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StackMigrationStatus.Descriptor instead.
func (StackMigrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{11}
}

// StackDependencyKind is the wiring type for a runtime cross-layer
// dependency (D29 after/watch). codegen renders the corresponding Terraform
// construct based on this value.
type StackDependencyKind int32

const (
	StackDependencyKind_STACK_DEPENDENCY_KIND_UNSPECIFIED  StackDependencyKind = 0
	StackDependencyKind_STACK_DEPENDENCY_KIND_REMOTE_STATE StackDependencyKind = 1
	StackDependencyKind_STACK_DEPENDENCY_KIND_DATA_SOURCE  StackDependencyKind = 2
	StackDependencyKind_STACK_DEPENDENCY_KIND_WATCH_ONLY   StackDependencyKind = 3
)

// Enum value maps for StackDependencyKind.
var (
	StackDependencyKind_name = map[int32]string{
		0: "STACK_DEPENDENCY_KIND_UNSPECIFIED",
		1: "STACK_DEPENDENCY_KIND_REMOTE_STATE",
		2: "STACK_DEPENDENCY_KIND_DATA_SOURCE",
		3: "STACK_DEPENDENCY_KIND_WATCH_ONLY",
	}
	StackDependencyKind_value = map[string]int32{
		"STACK_DEPENDENCY_KIND_UNSPECIFIED":  0,
		"STACK_DEPENDENCY_KIND_REMOTE_STATE": 1,
		"STACK_DEPENDENCY_KIND_DATA_SOURCE":  2,
		"STACK_DEPENDENCY_KIND_WATCH_ONLY":   3,
	}
)

func (x StackDependencyKind) Enum() *StackDependencyKind {
	p := new(StackDependencyKind)
	*p = x
	return p
}

func (x StackDependencyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StackDependencyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[12].Descriptor()
}

func (StackDependencyKind) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[12]
}

func (x StackDependencyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StackDependencyKind.Descriptor instead.
func (StackDependencyKind) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{12}
}

type CloudProvider int32

const (
	CloudProvider_CLOUD_PROVIDER_UNSPECIFIED CloudProvider = 0
	CloudProvider_CLOUD_PROVIDER_AWS         CloudProvider = 1
	CloudProvider_CLOUD_PROVIDER_ALIYUN      CloudProvider = 2
	CloudProvider_CLOUD_PROVIDER_AZURE       CloudProvider = 3
	CloudProvider_CLOUD_PROVIDER_GCP         CloudProvider = 4
)

// Enum value maps for CloudProvider.
var (
	CloudProvider_name = map[int32]string{
		0: "CLOUD_PROVIDER_UNSPECIFIED",
		1: "CLOUD_PROVIDER_AWS",
		2: "CLOUD_PROVIDER_ALIYUN",
		3: "CLOUD_PROVIDER_AZURE",
		4: "CLOUD_PROVIDER_GCP",
	}
	CloudProvider_value = map[string]int32{
		"CLOUD_PROVIDER_UNSPECIFIED": 0,
		"CLOUD_PROVIDER_AWS":         1,
		"CLOUD_PROVIDER_ALIYUN":      2,
		"CLOUD_PROVIDER_AZURE":       3,
		"CLOUD_PROVIDER_GCP":         4,
	}
)

func (x CloudProvider) Enum() *CloudProvider {
	p := new(CloudProvider)
	*p = x
	return p
}

func (x CloudProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[13].Descriptor()
}

func (CloudProvider) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[13]
}

func (x CloudProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudProvider.Descriptor instead.
func (CloudProvider) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{13}
}

type CloudAccountStatus int32

const (
	CloudAccountStatus_CLOUD_ACCOUNT_STATUS_UNSPECIFIED CloudAccountStatus = 0
	CloudAccountStatus_CLOUD_ACCOUNT_STATUS_ACTIVE      CloudAccountStatus = 1
	CloudAccountStatus_CLOUD_ACCOUNT_STATUS_SUSPENDED   CloudAccountStatus = 2
)

// Enum value maps for CloudAccountStatus.
var (
	CloudAccountStatus_name = map[int32]string{
		0: "CLOUD_ACCOUNT_STATUS_UNSPECIFIED",
		1: "CLOUD_ACCOUNT_STATUS_ACTIVE",
		2: "CLOUD_ACCOUNT_STATUS_SUSPENDED",
	}
	CloudAccountStatus_value = map[string]int32{
		"CLOUD_ACCOUNT_STATUS_UNSPECIFIED": 0,
		"CLOUD_ACCOUNT_STATUS_ACTIVE":      1,
		"CLOUD_ACCOUNT_STATUS_SUSPENDED":   2,
	}
)

func (x CloudAccountStatus) Enum() *CloudAccountStatus {
	p := new(CloudAccountStatus)
	*p = x
	return p
}

func (x CloudAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[14].Descriptor()
}

func (CloudAccountStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[14]
}

func (x CloudAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudAccountStatus.Descriptor instead.
func (CloudAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{14}
}

// ApprovalGate distinguishes the two mandatory review gates in the
// request lifecycle (D21): admission (pre-plan) and execution
// confirmation (pre-apply). See docs/12 §3.1.
type ApprovalGate int32

const (
	ApprovalGate_APPROVAL_GATE_UNSPECIFIED ApprovalGate = 0
	ApprovalGate_APPROVAL_GATE_PRE_PLAN    ApprovalGate = 1
	ApprovalGate_APPROVAL_GATE_PRE_APPLY   ApprovalGate = 2
	// Retroactive approval for break-glass runs (D30). Marks a run created
	// after an emergency apply to satisfy the 24h retroactive-approval window.
	ApprovalGate_APPROVAL_GATE_BREAK_GLASS_RETROACTIVE ApprovalGate = 3
)

// Enum value maps for ApprovalGate.
var (
	ApprovalGate_name = map[int32]string{
		0: "APPROVAL_GATE_UNSPECIFIED",
		1: "APPROVAL_GATE_PRE_PLAN",
		2: "APPROVAL_GATE_PRE_APPLY",
		3: "APPROVAL_GATE_BREAK_GLASS_RETROACTIVE",
	}
	ApprovalGate_value = map[string]int32{
		"APPROVAL_GATE_UNSPECIFIED":             0,
		"APPROVAL_GATE_PRE_PLAN":                1,
		"APPROVAL_GATE_PRE_APPLY":               2,
		"APPROVAL_GATE_BREAK_GLASS_RETROACTIVE": 3,
	}
)

func (x ApprovalGate) Enum() *ApprovalGate {
	p := new(ApprovalGate)
	*p = x
	return p
}

func (x ApprovalGate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalGate) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[15].Descriptor()
}

func (ApprovalGate) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[15]
}

func (x ApprovalGate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalGate.Descriptor instead.
func (ApprovalGate) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{15}
}

// ApprovalNodeMode is the decision semantics of an approval node, as
// declared in the approval flow DSL (docs/12 §2.3). The engine uses mode +
// required_count to determine if a node is satisfied:
//
//	any      = at least 1 approver (required_count ignored, treated as 1)
//	all      = all assigned approvers (required_count = total assignees)
//	majority = >50% of assignees (required_count = ceil(N/2))
//	quorum   = at least required_count approvers (count>=N expressed as quorum+N)
//
// Conditional routing (next_node based on outcome) is handled in the DSL,
// not in this enum — mode is purely the decision-aggregation rule.
type ApprovalNodeMode int32

const (
	ApprovalNodeMode_APPROVAL_NODE_MODE_UNSPECIFIED ApprovalNodeMode = 0
	ApprovalNodeMode_APPROVAL_NODE_MODE_ANY         ApprovalNodeMode = 1
	ApprovalNodeMode_APPROVAL_NODE_MODE_ALL         ApprovalNodeMode = 2
	ApprovalNodeMode_APPROVAL_NODE_MODE_MAJORITY    ApprovalNodeMode = 3
	ApprovalNodeMode_APPROVAL_NODE_MODE_QUORUM      ApprovalNodeMode = 4
)

// Enum value maps for ApprovalNodeMode.
var (
	ApprovalNodeMode_name = map[int32]string{
		0: "APPROVAL_NODE_MODE_UNSPECIFIED",
		1: "APPROVAL_NODE_MODE_ANY",
		2: "APPROVAL_NODE_MODE_ALL",
		3: "APPROVAL_NODE_MODE_MAJORITY",
		4: "APPROVAL_NODE_MODE_QUORUM",
	}
	ApprovalNodeMode_value = map[string]int32{
		"APPROVAL_NODE_MODE_UNSPECIFIED": 0,
		"APPROVAL_NODE_MODE_ANY":         1,
		"APPROVAL_NODE_MODE_ALL":         2,
		"APPROVAL_NODE_MODE_MAJORITY":    3,
		"APPROVAL_NODE_MODE_QUORUM":      4,
	}
)

func (x ApprovalNodeMode) Enum() *ApprovalNodeMode {
	p := new(ApprovalNodeMode)
	*p = x
	return p
}

func (x ApprovalNodeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalNodeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[16].Descriptor()
}

func (ApprovalNodeMode) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[16]
}

func (x ApprovalNodeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalNodeMode.Descriptor instead.
func (ApprovalNodeMode) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{16}
}

// ApprovalNodeStatus is the runtime status of a single approval node
// within a run (docs/04 §2.10 approval_node_runs.status).
type ApprovalNodeStatus int32

const (
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_UNSPECIFIED ApprovalNodeStatus = 0
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_PENDING     ApprovalNodeStatus = 1
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_APPROVED    ApprovalNodeStatus = 2
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_REJECTED    ApprovalNodeStatus = 3
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_SKIPPED     ApprovalNodeStatus = 4
	ApprovalNodeStatus_APPROVAL_NODE_STATUS_TIMEOUT     ApprovalNodeStatus = 5
)

// Enum value maps for ApprovalNodeStatus.
var (
	ApprovalNodeStatus_name = map[int32]string{
		0: "APPROVAL_NODE_STATUS_UNSPECIFIED",
		1: "APPROVAL_NODE_STATUS_PENDING",
		2: "APPROVAL_NODE_STATUS_APPROVED",
		3: "APPROVAL_NODE_STATUS_REJECTED",
		4: "APPROVAL_NODE_STATUS_SKIPPED",
		5: "APPROVAL_NODE_STATUS_TIMEOUT",
	}
	ApprovalNodeStatus_value = map[string]int32{
		"APPROVAL_NODE_STATUS_UNSPECIFIED": 0,
		"APPROVAL_NODE_STATUS_PENDING":     1,
		"APPROVAL_NODE_STATUS_APPROVED":    2,
		"APPROVAL_NODE_STATUS_REJECTED":    3,
		"APPROVAL_NODE_STATUS_SKIPPED":     4,
		"APPROVAL_NODE_STATUS_TIMEOUT":     5,
	}
)

func (x ApprovalNodeStatus) Enum() *ApprovalNodeStatus {
	p := new(ApprovalNodeStatus)
	*p = x
	return p
}

func (x ApprovalNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_v1_common_enum_proto_enumTypes[17].Descriptor()
}

func (ApprovalNodeStatus) Type() protoreflect.EnumType {
	return &file_platform_v1_common_enum_proto_enumTypes[17]
}

func (x ApprovalNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalNodeStatus.Descriptor instead.
func (ApprovalNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_v1_common_enum_proto_rawDescGZIP(), []int{17}
}

var File_platform_v1_common_enum_proto protoreflect.FileDescriptor

const file_platform_v1_common_enum_proto_rawDesc = "" +
	"\n" +
	"\x1dplatform/v1/common/enum.proto\x12\x19aether.platform.v1.common*g\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_TYPE_HUMAN\x10\x01\x12\x11\n" +
	"\rACTOR_TYPE_AI\x10\x02\x12\x15\n" +
	"\x11ACTOR_TYPE_SYSTEM\x10\x03*\xa4\x05\n" +
	"\rRequestStatus\x12\x1e\n" +
	"\x1aREQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REQUEST_STATUS_SUBMITTED\x10\x01\x12\x1d\n" +
	"\x19REQUEST_STATUS_GENERATING\x10\x02\x12$\n" +
	" REQUEST_STATUS_PENDING_ADMISSION\x10\x03\x12\x1b\n" +
	"\x17REQUEST_STATUS_PLANNING\x10\x04\x12\x1d\n" +
	"\x19REQUEST_STATUS_PLAN_READY\x10\x05\x12#\n" +
	"\x1fREQUEST_STATUS_PENDING_APPROVAL\x10\x06\x12\x1b\n" +
	"\x17REQUEST_STATUS_APPLYING\x10\a\x12\x1e\n" +
	"\x1aREQUEST_STATUS_RECONCILING\x10\b\x12\x1c\n" +
	"\x18REQUEST_STATUS_SUCCEEDED\x10\t\x12\x1b\n" +
	"\x17REQUEST_STATUS_REJECTED\x10\n" +
	"\x12\x1c\n" +
	"\x18REQUEST_STATUS_CANCELLED\x10\v\x12\x1a\n" +
	"\x16REQUEST_STATUS_EXPIRED\x10\f\x12#\n" +
	"\x1fREQUEST_STATUS_FAILED_RETRYABLE\x10\r\x12\"\n" +
	"\x1eREQUEST_STATUS_FAILED_TERMINAL\x10\x0e\x12!\n" +
	"\x1dREQUEST_STATUS_WAITING_MANUAL\x10\x0f\x12$\n" +
	" REQUEST_STATUS_RECONCILE_PENDING\x10\x10\x12!\n" +
	"\x1dREQUEST_STATUS_BLOCKED_POLICY\x10\x11\x12'\n" +
	"#REQUEST_STATUS_BLOCKED_STATE_HEALTH\x10\x12\x12\x1f\n" +
	"\x1bREQUEST_STATUS_PAUSED_DRIFT\x10\x13*\xab\x01\n" +
	"\rRequestSource\x12\x1e\n" +
	"\x1aREQUEST_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REQUEST_SOURCE_WEB\x10\x01\x12\x16\n" +
	"\x12REQUEST_SOURCE_CLI\x10\x02\x12\x17\n" +
	"\x13REQUEST_SOURCE_CICD\x10\x03\x12\x15\n" +
	"\x11REQUEST_SOURCE_AI\x10\x04\x12\x1a\n" +
	"\x16REQUEST_SOURCE_GATEWAY\x10\x05*u\n" +
	"\x10ApprovalDecision\x12!\n" +
	"\x1dAPPROVAL_DECISION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAPPROVAL_DECISION_APPROVED\x10\x01\x12\x1e\n" +
	"\x1aAPPROVAL_DECISION_REJECTED\x10\x02*\xbe\x01\n" +
	"\x11ApprovalRunStatus\x12#\n" +
	"\x1fAPPROVAL_RUN_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAPPROVAL_RUN_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cAPPROVAL_RUN_STATUS_APPROVED\x10\x02\x12 \n" +
	"\x1cAPPROVAL_RUN_STATUS_REJECTED\x10\x03\x12\x1f\n" +
	"\x1bAPPROVAL_RUN_STATUS_EXPIRED\x10\x04*\xa7\x01\n" +
	"\x0eArtifactStatus\x12\x1f\n" +
	"\x1bARTIFACT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ARTIFACT_STATUS_READY\x10\x01\x12\x1b\n" +
	"\x17ARTIFACT_STATUS_EXPIRED\x10\x02\x12\x1c\n" +
	"\x18ARTIFACT_STATUS_CONSUMED\x10\x03\x12\x1e\n" +
	"\x1aARTIFACT_STATUS_SUPERSEDED\x10\x04*a\n" +
	"\fGateSeverity\x12\x1d\n" +
	"\x19GATE_SEVERITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GATE_SEVERITY_ERROR\x10\x01\x12\x19\n" +
	"\x15GATE_SEVERITY_WARNING\x10\x02*\xb3\x01\n" +
	"\fModuleStatus\x12\x1d\n" +
	"\x19MODULE_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" MODULE_STATUS_PENDING_VALIDATION\x10\x01\x12\x1b\n" +
	"\x17MODULE_STATUS_VALIDATED\x10\x02\x12#\n" +
	"\x1fMODULE_STATUS_VALIDATION_FAILED\x10\x03\x12\x1c\n" +
	"\x18MODULE_STATUS_DEPRECATED\x10\x04*\xde\x01\n" +
	"\x11CatalogItemStatus\x12#\n" +
	"\x1fCATALOG_ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CATALOG_ITEM_STATUS_DRAFT\x10\x01\x12\x1e\n" +
	"\x1aCATALOG_ITEM_STATUS_ACTIVE\x10\x02\x12\"\n" +
	"\x1eCATALOG_ITEM_STATUS_DEPRECATED\x10\x03\x12 \n" +
	"\x1cCATALOG_ITEM_STATUS_ARCHIVED\x10\x04\x12\x1f\n" +
	"\x1bCATALOG_ITEM_STATUS_BLOCKED\x10\x05*m\n" +
	"\vCardinality\x12\x1b\n" +
	"\x17CARDINALITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CARDINALITY_SINGLE\x10\x01\x12\x14\n" +
	"\x10CARDINALITY_LIST\x10\x02\x12\x13\n" +
	"\x0fCARDINALITY_MAP\x10\x03*\xb9\x01\n" +
	"\x10StackGranularity\x12!\n" +
	"\x1dSTACK_GRANULARITY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSTACK_GRANULARITY_PER_COMPONENT\x10\x01\x12\x1f\n" +
	"\x1bSTACK_GRANULARITY_PER_SPACE\x10\x02\x12\x1e\n" +
	"\x1aSTACK_GRANULARITY_PER_TEAM\x10\x03\x12\x1c\n" +
	"\x18STACK_GRANULARITY_CUSTOM\x10\x04*\xdc\x01\n" +
	"\x14StackMigrationStatus\x12&\n" +
	"\"STACK_MIGRATION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSTACK_MIGRATION_STATUS_STABLE\x10\x01\x12,\n" +
	"(STACK_MIGRATION_STATUS_MIGRATION_PENDING\x10\x02\x12$\n" +
	" STACK_MIGRATION_STATUS_MIGRATING\x10\x03\x12%\n" +
	"!STACK_MIGRATION_STATUS_DEPRECATED\x10\x04*\xb1\x01\n" +
	"\x13StackDependencyKind\x12%\n" +
	"!STACK_DEPENDENCY_KIND_UNSPECIFIED\x10\x00\x12&\n" +
	"\"STACK_DEPENDENCY_KIND_REMOTE_STATE\x10\x01\x12%\n" +
	"!STACK_DEPENDENCY_KIND_DATA_SOURCE\x10\x02\x12$\n" +
	" STACK_DEPENDENCY_KIND_WATCH_ONLY\x10\x03*\x94\x01\n" +
	"\rCloudProvider\x12\x1e\n" +
	"\x1aCLOUD_PROVIDER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CLOUD_PROVIDER_AWS\x10\x01\x12\x19\n" +
	"\x15CLOUD_PROVIDER_ALIYUN\x10\x02\x12\x18\n" +
	"\x14CLOUD_PROVIDER_AZURE\x10\x03\x12\x16\n" +
	"\x12CLOUD_PROVIDER_GCP\x10\x04*\x7f\n" +
	"\x12CloudAccountStatus\x12$\n" +
	" CLOUD_ACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCLOUD_ACCOUNT_STATUS_ACTIVE\x10\x01\x12\"\n" +
	"\x1eCLOUD_ACCOUNT_STATUS_SUSPENDED\x10\x02*\x91\x01\n" +
	"\fApprovalGate\x12\x1d\n" +
	"\x19APPROVAL_GATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16APPROVAL_GATE_PRE_PLAN\x10\x01\x12\x1b\n" +
	"\x17APPROVAL_GATE_PRE_APPLY\x10\x02\x12)\n" +
	"%APPROVAL_GATE_BREAK_GLASS_RETROACTIVE\x10\x03*\xae\x01\n" +
	"\x10ApprovalNodeMode\x12\"\n" +
	"\x1eAPPROVAL_NODE_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16APPROVAL_NODE_MODE_ANY\x10\x01\x12\x1a\n" +
	"\x16APPROVAL_NODE_MODE_ALL\x10\x02\x12\x1f\n" +
	"\x1bAPPROVAL_NODE_MODE_MAJORITY\x10\x03\x12\x1d\n" +
	"\x19APPROVAL_NODE_MODE_QUORUM\x10\x04*\xe6\x01\n" +
	"\x12ApprovalNodeStatus\x12$\n" +
	" APPROVAL_NODE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAPPROVAL_NODE_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dAPPROVAL_NODE_STATUS_APPROVED\x10\x02\x12!\n" +
	"\x1dAPPROVAL_NODE_STATUS_REJECTED\x10\x03\x12 \n" +
	"\x1cAPPROVAL_NODE_STATUS_SKIPPED\x10\x04\x12 \n" +
	"\x1cAPPROVAL_NODE_STATUS_TIMEOUT\x10\x05BZZXgithub.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/common;commonv1b\x06proto3"

var (
	file_platform_v1_common_enum_proto_rawDescOnce sync.Once
	file_platform_v1_common_enum_proto_rawDescData []byte
)

func file_platform_v1_common_enum_proto_rawDescGZIP() []byte {
	file_platform_v1_common_enum_proto_rawDescOnce.Do(func() {
		file_platform_v1_common_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_v1_common_enum_proto_rawDesc), len(file_platform_v1_common_enum_proto_rawDesc)))
	})
	return file_platform_v1_common_enum_proto_rawDescData
}

var file_platform_v1_common_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 18)
var file_platform_v1_common_enum_proto_goTypes = []any{
	(ActorType)(0),            // 0: aether.platform.v1.common.ActorType
	(RequestStatus)(0),        // 1: aether.platform.v1.common.RequestStatus
	(RequestSource)(0),        // 2: aether.platform.v1.common.RequestSource
	(ApprovalDecision)(0),     // 3: aether.platform.v1.common.ApprovalDecision
	(ApprovalRunStatus)(0),    // 4: aether.platform.v1.common.ApprovalRunStatus
	(ArtifactStatus)(0),       // 5: aether.platform.v1.common.ArtifactStatus
	(GateSeverity)(0),         // 6: aether.platform.v1.common.GateSeverity
	(ModuleStatus)(0),         // 7: aether.platform.v1.common.ModuleStatus
	(CatalogItemStatus)(0),    // 8: aether.platform.v1.common.CatalogItemStatus
	(Cardinality)(0),          // 9: aether.platform.v1.common.Cardinality
	(StackGranularity)(0),     // 10: aether.platform.v1.common.StackGranularity
	(StackMigrationStatus)(0), // 11: aether.platform.v1.common.StackMigrationStatus
	(StackDependencyKind)(0),  // 12: aether.platform.v1.common.StackDependencyKind
	(CloudProvider)(0),        // 13: aether.platform.v1.common.CloudProvider
	(CloudAccountStatus)(0),   // 14: aether.platform.v1.common.CloudAccountStatus
	(ApprovalGate)(0),         // 15: aether.platform.v1.common.ApprovalGate
	(ApprovalNodeMode)(0),     // 16: aether.platform.v1.common.ApprovalNodeMode
	(ApprovalNodeStatus)(0),   // 17: aether.platform.v1.common.ApprovalNodeStatus
}
var file_platform_v1_common_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_v1_common_enum_proto_init() }
func file_platform_v1_common_enum_proto_init() {
	if File_platform_v1_common_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_common_enum_proto_rawDesc), len(file_platform_v1_common_enum_proto_rawDesc)),
			NumEnums:      18,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_v1_common_enum_proto_goTypes,
		DependencyIndexes: file_platform_v1_common_enum_proto_depIdxs,
		EnumInfos:         file_platform_v1_common_enum_proto_enumTypes,
	}.Build()
	File_platform_v1_common_enum_proto = out.File
	file_platform_v1_common_enum_proto_goTypes = nil
	file_platform_v1_common_enum_proto_depIdxs = nil
}
