// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/v1/catalog/srv.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_platform_v1_catalog_srv_proto protoreflect.FileDescriptor

const file_platform_v1_catalog_srv_proto_rawDesc = "" +
	"\n" +
	"\x1dplatform/v1/catalog/srv.proto\x12\x1aaether.platform.v1.catalog\x1a\x1dplatform/v1/catalog/dto.proto2\x96\x04\n" +
	"\x0eCatalogService\x12j\n" +
	"\tListItems\x12,.aether.platform.v1.catalog.ListItemsRequest\x1a-.aether.platform.v1.catalog.ListItemsResponse\"\x00\x12y\n" +
	"\x0eGetCatalogItem\x121.aether.platform.v1.catalog.GetCatalogItemRequest\x1a2.aether.platform.v1.catalog.GetCatalogItemResponse\"\x00\x12\x91\x01\n" +
	"\x16ListModuleDependencies\x129.aether.platform.v1.catalog.ListModuleDependenciesRequest\x1a:.aether.platform.v1.catalog.ListModuleDependenciesResponse\"\x00\x12\x88\x01\n" +
	"\x13ListAvailableStacks\x126.aether.platform.v1.catalog.ListAvailableStacksRequest\x1a7.aether.platform.v1.catalog.ListAvailableStacksResponse\"\x002\xb0\x03\n" +
	"\x13CatalogAdminService\x12\x85\x01\n" +
	"\x12PublishCatalogItem\x125.aether.platform.v1.catalog.PublishCatalogItemRequest\x1a6.aether.platform.v1.catalog.PublishCatalogItemResponse\"\x00\x12\x82\x01\n" +
	"\x11UpdateCatalogItem\x124.aether.platform.v1.catalog.UpdateCatalogItemRequest\x1a5.aether.platform.v1.catalog.UpdateCatalogItemResponse\"\x00\x12\x8b\x01\n" +
	"\x14DeprecateCatalogItem\x127.aether.platform.v1.catalog.DeprecateCatalogItemRequest\x1a8.aether.platform.v1.catalog.DeprecateCatalogItemResponse\"\x00B\\ZZgithub.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1/catalog;catalogv1b\x06proto3"

var file_platform_v1_catalog_srv_proto_goTypes = []any{
	(*ListItemsRequest)(nil),               // 0: aether.platform.v1.catalog.ListItemsRequest
	(*GetCatalogItemRequest)(nil),          // 1: aether.platform.v1.catalog.GetCatalogItemRequest
	(*ListModuleDependenciesRequest)(nil),  // 2: aether.platform.v1.catalog.ListModuleDependenciesRequest
	(*ListAvailableStacksRequest)(nil),     // 3: aether.platform.v1.catalog.ListAvailableStacksRequest
	(*PublishCatalogItemRequest)(nil),      // 4: aether.platform.v1.catalog.PublishCatalogItemRequest
	(*UpdateCatalogItemRequest)(nil),       // 5: aether.platform.v1.catalog.UpdateCatalogItemRequest
	(*DeprecateCatalogItemRequest)(nil),    // 6: aether.platform.v1.catalog.DeprecateCatalogItemRequest
	(*ListItemsResponse)(nil),              // 7: aether.platform.v1.catalog.ListItemsResponse
	(*GetCatalogItemResponse)(nil),         // 8: aether.platform.v1.catalog.GetCatalogItemResponse
	(*ListModuleDependenciesResponse)(nil), // 9: aether.platform.v1.catalog.ListModuleDependenciesResponse
	(*ListAvailableStacksResponse)(nil),    // 10: aether.platform.v1.catalog.ListAvailableStacksResponse
	(*PublishCatalogItemResponse)(nil),     // 11: aether.platform.v1.catalog.PublishCatalogItemResponse
	(*UpdateCatalogItemResponse)(nil),      // 12: aether.platform.v1.catalog.UpdateCatalogItemResponse
	(*DeprecateCatalogItemResponse)(nil),   // 13: aether.platform.v1.catalog.DeprecateCatalogItemResponse
}
var file_platform_v1_catalog_srv_proto_depIdxs = []int32{
	0,  // 0: aether.platform.v1.catalog.CatalogService.ListItems:input_type -> aether.platform.v1.catalog.ListItemsRequest
	1,  // 1: aether.platform.v1.catalog.CatalogService.GetCatalogItem:input_type -> aether.platform.v1.catalog.GetCatalogItemRequest
	2,  // 2: aether.platform.v1.catalog.CatalogService.ListModuleDependencies:input_type -> aether.platform.v1.catalog.ListModuleDependenciesRequest
	3,  // 3: aether.platform.v1.catalog.CatalogService.ListAvailableStacks:input_type -> aether.platform.v1.catalog.ListAvailableStacksRequest
	4,  // 4: aether.platform.v1.catalog.CatalogAdminService.PublishCatalogItem:input_type -> aether.platform.v1.catalog.PublishCatalogItemRequest
	5,  // 5: aether.platform.v1.catalog.CatalogAdminService.UpdateCatalogItem:input_type -> aether.platform.v1.catalog.UpdateCatalogItemRequest
	6,  // 6: aether.platform.v1.catalog.CatalogAdminService.DeprecateCatalogItem:input_type -> aether.platform.v1.catalog.DeprecateCatalogItemRequest
	7,  // 7: aether.platform.v1.catalog.CatalogService.ListItems:output_type -> aether.platform.v1.catalog.ListItemsResponse
	8,  // 8: aether.platform.v1.catalog.CatalogService.GetCatalogItem:output_type -> aether.platform.v1.catalog.GetCatalogItemResponse
	9,  // 9: aether.platform.v1.catalog.CatalogService.ListModuleDependencies:output_type -> aether.platform.v1.catalog.ListModuleDependenciesResponse
	10, // 10: aether.platform.v1.catalog.CatalogService.ListAvailableStacks:output_type -> aether.platform.v1.catalog.ListAvailableStacksResponse
	11, // 11: aether.platform.v1.catalog.CatalogAdminService.PublishCatalogItem:output_type -> aether.platform.v1.catalog.PublishCatalogItemResponse
	12, // 12: aether.platform.v1.catalog.CatalogAdminService.UpdateCatalogItem:output_type -> aether.platform.v1.catalog.UpdateCatalogItemResponse
	13, // 13: aether.platform.v1.catalog.CatalogAdminService.DeprecateCatalogItem:output_type -> aether.platform.v1.catalog.DeprecateCatalogItemResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_platform_v1_catalog_srv_proto_init() }
func file_platform_v1_catalog_srv_proto_init() {
	if File_platform_v1_catalog_srv_proto != nil {
		return
	}
	file_platform_v1_catalog_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_v1_catalog_srv_proto_rawDesc), len(file_platform_v1_catalog_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_platform_v1_catalog_srv_proto_goTypes,
		DependencyIndexes: file_platform_v1_catalog_srv_proto_depIdxs,
	}.Build()
	File_platform_v1_catalog_srv_proto = out.File
	file_platform_v1_catalog_srv_proto_goTypes = nil
	file_platform_v1_catalog_srv_proto_depIdxs = nil
}
