// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/v1/approval.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ApprovalServiceName is the fully-qualified name of the ApprovalService service.
	ApprovalServiceName = "aether.platform.v1.ApprovalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ApprovalServiceDecideApprovalProcedure is the fully-qualified name of the ApprovalService's
	// DecideApproval RPC.
	ApprovalServiceDecideApprovalProcedure = "/aether.platform.v1.ApprovalService/DecideApproval"
)

// ApprovalServiceClient is a client for the aether.platform.v1.ApprovalService service.
type ApprovalServiceClient interface {
	DecideApproval(context.Context, *connect.Request[v1.DecideApprovalRequest]) (*connect.Response[v1.DecideApprovalResponse], error)
}

// NewApprovalServiceClient constructs a client for the aether.platform.v1.ApprovalService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewApprovalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApprovalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	approvalServiceMethods := v1.File_platform_v1_approval_proto.Services().ByName("ApprovalService").Methods()
	return &approvalServiceClient{
		decideApproval: connect.NewClient[v1.DecideApprovalRequest, v1.DecideApprovalResponse](
			httpClient,
			baseURL+ApprovalServiceDecideApprovalProcedure,
			connect.WithSchema(approvalServiceMethods.ByName("DecideApproval")),
			connect.WithClientOptions(opts...),
		),
	}
}

// approvalServiceClient implements ApprovalServiceClient.
type approvalServiceClient struct {
	decideApproval *connect.Client[v1.DecideApprovalRequest, v1.DecideApprovalResponse]
}

// DecideApproval calls aether.platform.v1.ApprovalService.DecideApproval.
func (c *approvalServiceClient) DecideApproval(ctx context.Context, req *connect.Request[v1.DecideApprovalRequest]) (*connect.Response[v1.DecideApprovalResponse], error) {
	return c.decideApproval.CallUnary(ctx, req)
}

// ApprovalServiceHandler is an implementation of the aether.platform.v1.ApprovalService service.
type ApprovalServiceHandler interface {
	DecideApproval(context.Context, *connect.Request[v1.DecideApprovalRequest]) (*connect.Response[v1.DecideApprovalResponse], error)
}

// NewApprovalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewApprovalServiceHandler(svc ApprovalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	approvalServiceMethods := v1.File_platform_v1_approval_proto.Services().ByName("ApprovalService").Methods()
	approvalServiceDecideApprovalHandler := connect.NewUnaryHandler(
		ApprovalServiceDecideApprovalProcedure,
		svc.DecideApproval,
		connect.WithSchema(approvalServiceMethods.ByName("DecideApproval")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aether.platform.v1.ApprovalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ApprovalServiceDecideApprovalProcedure:
			approvalServiceDecideApprovalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedApprovalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedApprovalServiceHandler struct{}

func (UnimplementedApprovalServiceHandler) DecideApproval(context.Context, *connect.Request[v1.DecideApprovalRequest]) (*connect.Response[v1.DecideApprovalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.ApprovalService.DecideApproval is not implemented"))
}
