// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/v1/catalog.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CatalogServiceName is the fully-qualified name of the CatalogService service.
	CatalogServiceName = "aether.platform.v1.CatalogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CatalogServiceListItemsProcedure is the fully-qualified name of the CatalogService's ListItems
	// RPC.
	CatalogServiceListItemsProcedure = "/aether.platform.v1.CatalogService/ListItems"
	// CatalogServiceGetCatalogItemProcedure is the fully-qualified name of the CatalogService's
	// GetCatalogItem RPC.
	CatalogServiceGetCatalogItemProcedure = "/aether.platform.v1.CatalogService/GetCatalogItem"
)

// CatalogServiceClient is a client for the aether.platform.v1.CatalogService service.
type CatalogServiceClient interface {
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
	GetCatalogItem(context.Context, *connect.Request[v1.GetCatalogItemRequest]) (*connect.Response[v1.GetCatalogItemResponse], error)
}

// NewCatalogServiceClient constructs a client for the aether.platform.v1.CatalogService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCatalogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CatalogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	catalogServiceMethods := v1.File_platform_v1_catalog_proto.Services().ByName("CatalogService").Methods()
	return &catalogServiceClient{
		listItems: connect.NewClient[v1.ListItemsRequest, v1.ListItemsResponse](
			httpClient,
			baseURL+CatalogServiceListItemsProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("ListItems")),
			connect.WithClientOptions(opts...),
		),
		getCatalogItem: connect.NewClient[v1.GetCatalogItemRequest, v1.GetCatalogItemResponse](
			httpClient,
			baseURL+CatalogServiceGetCatalogItemProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("GetCatalogItem")),
			connect.WithClientOptions(opts...),
		),
	}
}

// catalogServiceClient implements CatalogServiceClient.
type catalogServiceClient struct {
	listItems      *connect.Client[v1.ListItemsRequest, v1.ListItemsResponse]
	getCatalogItem *connect.Client[v1.GetCatalogItemRequest, v1.GetCatalogItemResponse]
}

// ListItems calls aether.platform.v1.CatalogService.ListItems.
func (c *catalogServiceClient) ListItems(ctx context.Context, req *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return c.listItems.CallUnary(ctx, req)
}

// GetCatalogItem calls aether.platform.v1.CatalogService.GetCatalogItem.
func (c *catalogServiceClient) GetCatalogItem(ctx context.Context, req *connect.Request[v1.GetCatalogItemRequest]) (*connect.Response[v1.GetCatalogItemResponse], error) {
	return c.getCatalogItem.CallUnary(ctx, req)
}

// CatalogServiceHandler is an implementation of the aether.platform.v1.CatalogService service.
type CatalogServiceHandler interface {
	ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error)
	GetCatalogItem(context.Context, *connect.Request[v1.GetCatalogItemRequest]) (*connect.Response[v1.GetCatalogItemResponse], error)
}

// NewCatalogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCatalogServiceHandler(svc CatalogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	catalogServiceMethods := v1.File_platform_v1_catalog_proto.Services().ByName("CatalogService").Methods()
	catalogServiceListItemsHandler := connect.NewUnaryHandler(
		CatalogServiceListItemsProcedure,
		svc.ListItems,
		connect.WithSchema(catalogServiceMethods.ByName("ListItems")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceGetCatalogItemHandler := connect.NewUnaryHandler(
		CatalogServiceGetCatalogItemProcedure,
		svc.GetCatalogItem,
		connect.WithSchema(catalogServiceMethods.ByName("GetCatalogItem")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aether.platform.v1.CatalogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CatalogServiceListItemsProcedure:
			catalogServiceListItemsHandler.ServeHTTP(w, r)
		case CatalogServiceGetCatalogItemProcedure:
			catalogServiceGetCatalogItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCatalogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCatalogServiceHandler struct{}

func (UnimplementedCatalogServiceHandler) ListItems(context.Context, *connect.Request[v1.ListItemsRequest]) (*connect.Response[v1.ListItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.CatalogService.ListItems is not implemented"))
}

func (UnimplementedCatalogServiceHandler) GetCatalogItem(context.Context, *connect.Request[v1.GetCatalogItemRequest]) (*connect.Response[v1.GetCatalogItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.CatalogService.GetCatalogItem is not implemented"))
}
