// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/v1/dependency.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DependencyServiceName is the fully-qualified name of the DependencyService service.
	DependencyServiceName = "aether.platform.v1.DependencyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DependencyServiceListModuleDependenciesProcedure is the fully-qualified name of the
	// DependencyService's ListModuleDependencies RPC.
	DependencyServiceListModuleDependenciesProcedure = "/aether.platform.v1.DependencyService/ListModuleDependencies"
	// DependencyServiceListAvailableStacksProcedure is the fully-qualified name of the
	// DependencyService's ListAvailableStacks RPC.
	DependencyServiceListAvailableStacksProcedure = "/aether.platform.v1.DependencyService/ListAvailableStacks"
)

// DependencyServiceClient is a client for the aether.platform.v1.DependencyService service.
type DependencyServiceClient interface {
	// 查询某个模块版本的依赖列表（前端据此渲染"选 VPC"等选择器）。
	ListModuleDependencies(context.Context, *connect.Request[v1.ListModuleDependenciesRequest]) (*connect.Response[v1.ListModuleDependenciesResponse], error)
	// 查询某个依赖可用的上游 stack（如选了 VPC 模块，返回已有的 VPC stack 列表）。
	// 这些 stack 的 outputs 通过 terraform_remote_state 注入到 codegen。
	ListAvailableStacks(context.Context, *connect.Request[v1.ListAvailableStacksRequest]) (*connect.Response[v1.ListAvailableStacksResponse], error)
}

// NewDependencyServiceClient constructs a client for the aether.platform.v1.DependencyService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDependencyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DependencyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dependencyServiceMethods := v1.File_platform_v1_dependency_proto.Services().ByName("DependencyService").Methods()
	return &dependencyServiceClient{
		listModuleDependencies: connect.NewClient[v1.ListModuleDependenciesRequest, v1.ListModuleDependenciesResponse](
			httpClient,
			baseURL+DependencyServiceListModuleDependenciesProcedure,
			connect.WithSchema(dependencyServiceMethods.ByName("ListModuleDependencies")),
			connect.WithClientOptions(opts...),
		),
		listAvailableStacks: connect.NewClient[v1.ListAvailableStacksRequest, v1.ListAvailableStacksResponse](
			httpClient,
			baseURL+DependencyServiceListAvailableStacksProcedure,
			connect.WithSchema(dependencyServiceMethods.ByName("ListAvailableStacks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dependencyServiceClient implements DependencyServiceClient.
type dependencyServiceClient struct {
	listModuleDependencies *connect.Client[v1.ListModuleDependenciesRequest, v1.ListModuleDependenciesResponse]
	listAvailableStacks    *connect.Client[v1.ListAvailableStacksRequest, v1.ListAvailableStacksResponse]
}

// ListModuleDependencies calls aether.platform.v1.DependencyService.ListModuleDependencies.
func (c *dependencyServiceClient) ListModuleDependencies(ctx context.Context, req *connect.Request[v1.ListModuleDependenciesRequest]) (*connect.Response[v1.ListModuleDependenciesResponse], error) {
	return c.listModuleDependencies.CallUnary(ctx, req)
}

// ListAvailableStacks calls aether.platform.v1.DependencyService.ListAvailableStacks.
func (c *dependencyServiceClient) ListAvailableStacks(ctx context.Context, req *connect.Request[v1.ListAvailableStacksRequest]) (*connect.Response[v1.ListAvailableStacksResponse], error) {
	return c.listAvailableStacks.CallUnary(ctx, req)
}

// DependencyServiceHandler is an implementation of the aether.platform.v1.DependencyService
// service.
type DependencyServiceHandler interface {
	// 查询某个模块版本的依赖列表（前端据此渲染"选 VPC"等选择器）。
	ListModuleDependencies(context.Context, *connect.Request[v1.ListModuleDependenciesRequest]) (*connect.Response[v1.ListModuleDependenciesResponse], error)
	// 查询某个依赖可用的上游 stack（如选了 VPC 模块，返回已有的 VPC stack 列表）。
	// 这些 stack 的 outputs 通过 terraform_remote_state 注入到 codegen。
	ListAvailableStacks(context.Context, *connect.Request[v1.ListAvailableStacksRequest]) (*connect.Response[v1.ListAvailableStacksResponse], error)
}

// NewDependencyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDependencyServiceHandler(svc DependencyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dependencyServiceMethods := v1.File_platform_v1_dependency_proto.Services().ByName("DependencyService").Methods()
	dependencyServiceListModuleDependenciesHandler := connect.NewUnaryHandler(
		DependencyServiceListModuleDependenciesProcedure,
		svc.ListModuleDependencies,
		connect.WithSchema(dependencyServiceMethods.ByName("ListModuleDependencies")),
		connect.WithHandlerOptions(opts...),
	)
	dependencyServiceListAvailableStacksHandler := connect.NewUnaryHandler(
		DependencyServiceListAvailableStacksProcedure,
		svc.ListAvailableStacks,
		connect.WithSchema(dependencyServiceMethods.ByName("ListAvailableStacks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aether.platform.v1.DependencyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DependencyServiceListModuleDependenciesProcedure:
			dependencyServiceListModuleDependenciesHandler.ServeHTTP(w, r)
		case DependencyServiceListAvailableStacksProcedure:
			dependencyServiceListAvailableStacksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDependencyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDependencyServiceHandler struct{}

func (UnimplementedDependencyServiceHandler) ListModuleDependencies(context.Context, *connect.Request[v1.ListModuleDependenciesRequest]) (*connect.Response[v1.ListModuleDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.DependencyService.ListModuleDependencies is not implemented"))
}

func (UnimplementedDependencyServiceHandler) ListAvailableStacks(context.Context, *connect.Request[v1.ListAvailableStacksRequest]) (*connect.Response[v1.ListAvailableStacksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.DependencyService.ListAvailableStacks is not implemented"))
}
