// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/v1/planning.proto

package platformv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/xuanwu-labs/selfservice-iac/server/internal/proto/platform/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PlanningServiceName is the fully-qualified name of the PlanningService service.
	PlanningServiceName = "aether.platform.v1.PlanningService"
	// ArtifactServiceName is the fully-qualified name of the ArtifactService service.
	ArtifactServiceName = "aether.platform.v1.ArtifactService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PlanningServiceStartPlanProcedure is the fully-qualified name of the PlanningService's StartPlan
	// RPC.
	PlanningServiceStartPlanProcedure = "/aether.platform.v1.PlanningService/StartPlan"
	// ArtifactServiceGetArtifactProcedure is the fully-qualified name of the ArtifactService's
	// GetArtifact RPC.
	ArtifactServiceGetArtifactProcedure = "/aether.platform.v1.ArtifactService/GetArtifact"
)

// PlanningServiceClient is a client for the aether.platform.v1.PlanningService service.
type PlanningServiceClient interface {
	StartPlan(context.Context, *connect.Request[v1.StartPlanRequest]) (*connect.Response[v1.StartPlanResponse], error)
}

// NewPlanningServiceClient constructs a client for the aether.platform.v1.PlanningService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPlanningServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PlanningServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	planningServiceMethods := v1.File_platform_v1_planning_proto.Services().ByName("PlanningService").Methods()
	return &planningServiceClient{
		startPlan: connect.NewClient[v1.StartPlanRequest, v1.StartPlanResponse](
			httpClient,
			baseURL+PlanningServiceStartPlanProcedure,
			connect.WithSchema(planningServiceMethods.ByName("StartPlan")),
			connect.WithClientOptions(opts...),
		),
	}
}

// planningServiceClient implements PlanningServiceClient.
type planningServiceClient struct {
	startPlan *connect.Client[v1.StartPlanRequest, v1.StartPlanResponse]
}

// StartPlan calls aether.platform.v1.PlanningService.StartPlan.
func (c *planningServiceClient) StartPlan(ctx context.Context, req *connect.Request[v1.StartPlanRequest]) (*connect.Response[v1.StartPlanResponse], error) {
	return c.startPlan.CallUnary(ctx, req)
}

// PlanningServiceHandler is an implementation of the aether.platform.v1.PlanningService service.
type PlanningServiceHandler interface {
	StartPlan(context.Context, *connect.Request[v1.StartPlanRequest]) (*connect.Response[v1.StartPlanResponse], error)
}

// NewPlanningServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPlanningServiceHandler(svc PlanningServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	planningServiceMethods := v1.File_platform_v1_planning_proto.Services().ByName("PlanningService").Methods()
	planningServiceStartPlanHandler := connect.NewUnaryHandler(
		PlanningServiceStartPlanProcedure,
		svc.StartPlan,
		connect.WithSchema(planningServiceMethods.ByName("StartPlan")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aether.platform.v1.PlanningService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PlanningServiceStartPlanProcedure:
			planningServiceStartPlanHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPlanningServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPlanningServiceHandler struct{}

func (UnimplementedPlanningServiceHandler) StartPlan(context.Context, *connect.Request[v1.StartPlanRequest]) (*connect.Response[v1.StartPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.PlanningService.StartPlan is not implemented"))
}

// ArtifactServiceClient is a client for the aether.platform.v1.ArtifactService service.
type ArtifactServiceClient interface {
	GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error)
}

// NewArtifactServiceClient constructs a client for the aether.platform.v1.ArtifactService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArtifactServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArtifactServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	artifactServiceMethods := v1.File_platform_v1_planning_proto.Services().ByName("ArtifactService").Methods()
	return &artifactServiceClient{
		getArtifact: connect.NewClient[v1.GetArtifactRequest, v1.GetArtifactResponse](
			httpClient,
			baseURL+ArtifactServiceGetArtifactProcedure,
			connect.WithSchema(artifactServiceMethods.ByName("GetArtifact")),
			connect.WithClientOptions(opts...),
		),
	}
}

// artifactServiceClient implements ArtifactServiceClient.
type artifactServiceClient struct {
	getArtifact *connect.Client[v1.GetArtifactRequest, v1.GetArtifactResponse]
}

// GetArtifact calls aether.platform.v1.ArtifactService.GetArtifact.
func (c *artifactServiceClient) GetArtifact(ctx context.Context, req *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error) {
	return c.getArtifact.CallUnary(ctx, req)
}

// ArtifactServiceHandler is an implementation of the aether.platform.v1.ArtifactService service.
type ArtifactServiceHandler interface {
	GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error)
}

// NewArtifactServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArtifactServiceHandler(svc ArtifactServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	artifactServiceMethods := v1.File_platform_v1_planning_proto.Services().ByName("ArtifactService").Methods()
	artifactServiceGetArtifactHandler := connect.NewUnaryHandler(
		ArtifactServiceGetArtifactProcedure,
		svc.GetArtifact,
		connect.WithSchema(artifactServiceMethods.ByName("GetArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aether.platform.v1.ArtifactService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArtifactServiceGetArtifactProcedure:
			artifactServiceGetArtifactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArtifactServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArtifactServiceHandler struct{}

func (UnimplementedArtifactServiceHandler) GetArtifact(context.Context, *connect.Request[v1.GetArtifactRequest]) (*connect.Response[v1.GetArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aether.platform.v1.ArtifactService.GetArtifact is not implemented"))
}
