// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/uptrace/opentelemetry-go-extra/otelzap"
	"github.com/xuanwu-labs/selfservice-iac/server/api"
	"github.com/xuanwu-labs/selfservice-iac/server/api/connect"
	"github.com/xuanwu-labs/selfservice-iac/server/core"
	"github.com/xuanwu-labs/selfservice-iac/server/data"
	"github.com/xuanwu-labs/selfservice-iac/server/internal/config"
	"github.com/xuanwu-labs/selfservice-iac/server/internal/server"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp builds the server app via wire. cfg is loaded by main.go
// (before wire) from flags + env + yaml — wire receives it as a bound value.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	logger := provideLogger(cfg)
	context := provideAppContext()
	pool, cleanup, err := data.NewPgxPool(context, cfg)
	if err != nil {
		return nil, nil, err
	}
	v := api.NewPingFunc(pool)
	handler := server.ProvideMetricsHandler()
	catalogHandler := connect.NewCatalogHandler()
	serverConfig, err := server.ProvideServerConfig(catalogHandler, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine := server.NewHTTPServer(logger, v, handler, serverConfig)
	serverServer := server.NewServer(cfg, engine, serverConfig, logger)
	app := &App{
		Config: cfg,
		Logger: logger,
		Server: serverServer,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App is the assembled platform server — the output of wire.
type App struct {
	Config *config.Config
	Logger *otelzap.Logger
	Server *server.Server
}

// provideLogger returns a trace-aware otelzap logger. OTel SDK is initialized
// in main.go BEFORE wire runs, so the global TracerProvider is ready when this
// executes — the returned logger carries trace_id in every Ctx() log call (D41).
func provideLogger(cfg *config.Config) *otelzap.Logger {
	var base *zap.Logger
	if cfg.LogLevel == "debug" {
		base, _ = zap.NewDevelopment()
	} else {
		base, _ = zap.NewProduction()
	}
	return otelzap.New(base)
}

// provideAppContext supplies the background context used by data-layer
// providers (e.g. pgxpool construction).
func provideAppContext() context.Context { return context.Background() }

// allProviders aggregates every layer's ProviderSet. Adding a new package
// means adding its ProviderSet here — nothing else changes in wire.go.
var allProviders = wire.NewSet(config.ProviderSet, data.ProviderSet, core.ProviderSet, api.ProviderSet, connect.ProviderSet, server.ProviderSet, provideLogger,
	provideAppContext, wire.Struct(new(App), "*"),
)
